// examples/chat-demo/src/lib/components/Composer.svelte
<script lang="ts">
	import ArrowUp from '@lucide/svelte/icons/arrow-up';
	import Boxes from '@lucide/svelte/icons/boxes';
	import Cable from '@lucide/svelte/icons/cable';
	import Check from '@lucide/svelte/icons/check';
	import ChevronRight from '@lucide/svelte/icons/chevron-right';
	import Plus from '@lucide/svelte/icons/plus';
	import { CHAT_MODELS, DEFAULT_CHAT_MODEL } from '$lib/chatModels';
	import { connectorIconSrc } from '$lib/connectorIcons';
	import { connectorsCache } from '$lib/connectorsCache.svelte';

	type Flyout = 'models' | 'connectors';

	interface Props {
		value?: string;
		sending?: boolean;
		docked?: boolean;
		/** When true, model + connectors are read-only (existing chat). */
		configLocked?: boolean;
		selectedConnectorIds?: number[];
		selectedModel?: string;
		onsend?: () => void;
		class?: string;
	}

	let {
		value = $bindable(''),
		sending = false,
		docked = false,
		configLocked = false,
		selectedConnectorIds = $bindable<number[]>([]),
		selectedModel = $bindable(DEFAULT_CHAT_MODEL as string),
		onsend,
		class: className = ''
	}: Props = $props();

	const ROOT_ITEMS = [
		{ id: 'models' as const, label: 'Models', icon: Boxes },
		{ id: 'connectors' as const, label: 'Connectors', icon: Cable }
	];

	let menuOpen = $state(false);
	let flyout = $state<Flyout | null>(null);
	let connectorQuery = $state('');
	let menuRoot: HTMLDivElement | undefined;
	let textareaEl: HTMLTextAreaElement | undefined;

	const normalizedConnectorQuery = $derived(connectorQuery.trim().toLowerCase());

	const filteredConnectors = $derived(
		connectorsCache.connectors.filter((connector) => {
			if (!normalizedConnectorQuery) return true;
			return (
				connector.name.toLowerCase().includes(normalizedConnectorQuery) ||
				connector.type.toLowerCase().includes(normalizedConnectorQuery)
			);
		})
	);

	const selectedModelLabel = $derived(
		CHAT_MODELS.find((model) => model.id === selectedModel)?.label ??
			selectedModel.replace(/^MODEL_/, '').replaceAll('_', ' ')
	);

	const selectedChips = $derived(
		selectedConnectorIds.map((id) => {
			const match = connectorsCache.connectors.find((connector) => connector.id === id);
			return {
				id,
				name: match?.name ?? `Connector ${id}`,
				type: match?.type ?? 'UNKNOWN'
			};
		})
	);

	function openMenu(initialFlyout: Flyout | null = null) {
		if (configLocked) return;
		menuOpen = true;
		flyout = initialFlyout;
		connectorQuery = '';
		if (initialFlyout === 'connectors') {
			void connectorsCache.load();
		}
	}

	function closeMenu() {
		menuOpen = false;
		flyout = null;
		connectorQuery = '';
	}

	function toggleMenu() {
		if (configLocked) return;
		if (menuOpen) {
			closeMenu();
			return;
		}
		openMenu();
	}

	function openFlyout(next: Flyout) {
		if (configLocked) return;
		if (flyout === next) return;
		flyout = next;
		connectorQuery = '';
		if (next === 'connectors') {
			void connectorsCache.load();
		}
	}

	function selectModel(modelId: string) {
		if (configLocked) return;
		selectedModel = modelId;
		closeMenu();
		textareaEl?.focus();
	}

	function toggleConnector(connector: { id: number; name: string }) {
		if (configLocked) return;

		if (selectedConnectorIds.includes(connector.id)) {
			selectedConnectorIds = selectedConnectorIds.filter((id) => id !== connector.id);
		} else {
			selectedConnectorIds = [...selectedConnectorIds, connector.id];
		}
	}

	function removeConnector(id: number) {
		if (configLocked) return;
		selectedConnectorIds = selectedConnectorIds.filter((selectedId) => selectedId !== id);
	}

	const TEXTAREA_MAX_PX = 160;

	function resizeTextarea() {
		const el = textareaEl;
		if (!el) return;
		el.style.height = '0px';
		const next = Math.min(el.scrollHeight, TEXTAREA_MAX_PX);
		el.style.height = `${next}px`;
		el.style.overflowY = el.scrollHeight > TEXTAREA_MAX_PX ? 'auto' : 'hidden';
	}

	function insertNewline() {
		const el = textareaEl;
		if (!el) return;
		const start = el.selectionStart;
		const end = el.selectionEnd;
		value = `${value.slice(0, start)}\n${value.slice(end)}`;
		queueMicrotask(() => {
			el.selectionStart = el.selectionEnd = start + 1;
			resizeTextarea();
			el.focus();
		});
	}

	function handleComposerKeydown(event: KeyboardEvent) {
		if (event.key !== 'Enter') return;

		// Cmd/Ctrl+Enter or Shift+Enter → new line (grows until max, then scrolls).
		if (event.metaKey || event.ctrlKey || event.shiftKey) {
			event.preventDefault();
			insertNewline();
			return;
		}

		event.preventDefault();
		onsend?.();
	}

	$effect(() => {
		value;
		queueMicrotask(resizeTextarea);
	});

	function handleWindowKeydown(event: KeyboardEvent) {
		if (event.key === 'Escape' && menuOpen) {
			event.preventDefault();
			if (flyout) {
				flyout = null;
				connectorQuery = '';
				return;
			}
			closeMenu();
		}
	}

	function handleWindowPointerDown(event: PointerEvent) {
		if (!menuOpen || !menuRoot) return;
		const target = event.target;
		if (!(target instanceof Node) || menuRoot.contains(target)) return;
		closeMenu();
	}

	function attachMenuRoot(element: HTMLDivElement) {
		menuRoot = element;
		return () => {
			if (menuRoot === element) menuRoot = undefined;
		};
	}

	function attachConnectorSearchInput(element: HTMLInputElement) {
		queueMicrotask(() => element.focus());
	}

	function attachTextarea(element: HTMLTextAreaElement) {
		textareaEl = element;
		queueMicrotask(resizeTextarea);
		return () => {
			if (textareaEl === element) textareaEl = undefined;
		};
	}
</script>

<svelte:window onkeydown={handleWindowKeydown} onpointerdown={handleWindowPointerDown} />

<div class={['composer', docked && 'docked', className]}>
	<textarea
		{@attach attachTextarea}
		bind:value
		onkeydown={handleComposerKeydown}
		rows="1"
		placeholder="Plan, @ for context, / for commands"
		aria-label="Message"
	></textarea>

	<div class="composer-toolbar">
		<div class="toolbar-left" {@attach attachMenuRoot}>
			{#if !configLocked}
				<button
					type="button"
					class="icon-circle"
					class:active={menuOpen || selectedConnectorIds.length > 0}
					aria-label="Composer settings"
					aria-haspopup="menu"
					aria-expanded={menuOpen}
					onclick={toggleMenu}
				>
					<Plus size={15} strokeWidth={1.5} aria-hidden="true" />
				</button>
			{/if}

			{#if selectedChips.length > 0}
				<div class="meta-row">
					<div class="connector-stack" aria-label="Attached connectors">
						{#each selectedChips.slice(0, 3) as chip (chip.id)}
							{#if configLocked}
								<span class="connector-dot" aria-label={chip.name}>
									<img src={connectorIconSrc(chip.type)} alt="" />
									<span class="connector-tip">{chip.name}</span>
								</span>
							{:else}
								<button
									type="button"
									class="connector-dot"
									aria-label={`Remove ${chip.name}`}
									onclick={() => removeConnector(chip.id)}
								>
									<img src={connectorIconSrc(chip.type)} alt="" />
									<span class="connector-tip">{chip.name}</span>
								</button>
							{/if}
						{/each}
						{#if selectedChips.length > 3}
							<button
								type="button"
								class="connector-more"
								aria-label={`${selectedChips.length - 3} more connectors`}
								onclick={() => openMenu('connectors')}
								disabled={configLocked}
							>
								+{selectedChips.length - 3}
								<span class="connector-tip"
									>{selectedChips.length - 3} more</span
								>
							</button>
						{/if}
					</div>
				</div>
			{/if}

			{#if menuOpen && !configLocked}
				<div class="menu-shell">
					<div class="popover root-popover" role="menu" aria-label="Composer settings">
						<div class="menu-section">
							{#each ROOT_ITEMS as item (item.id)}
								<button
									type="button"
									class="menu-row"
									class:flyout-open={flyout === item.id}
									role="menuitem"
									aria-haspopup="menu"
									aria-expanded={flyout === item.id}
									onmouseenter={() => openFlyout(item.id)}
									onfocus={() => openFlyout(item.id)}
									onclick={() => openFlyout(item.id)}
								>
									<span class="menu-row-main">
										<span class="menu-icon" aria-hidden="true">
											<item.icon size={14} strokeWidth={1.5} />
										</span>
										{item.label}
									</span>
									<span class="menu-meta">
										{#if item.id === 'connectors' && selectedConnectorIds.length > 0}
											<span class="badge">{selectedConnectorIds.length}</span>
										{:else if item.id === 'models'}
											<span class="menu-hint">{selectedModelLabel}</span>
										{/if}
										<ChevronRight class="chevron" size={14} strokeWidth={1.5} aria-hidden="true" />
									</span>
								</button>
							{/each}
						</div>
					</div>

					{#if flyout === 'models'}
						<div class="popover flyout-popover" role="menu" aria-label="Models">
							<div class="menu-section models-list">
								{#each CHAT_MODELS as model (model.id)}
									<button
										type="button"
										class="menu-row model-row"
										class:selected={selectedModel === model.id}
										role="menuitem"
										onclick={() => selectModel(model.id)}
									>
										<span class="model-row-main">
											<img
												class="model-logo"
												src={connectorIconSrc(model.provider)}
												alt=""
											/>
											<span class="menu-row-main column">
												<span class="model-title">{model.label}</span>
												<span class="model-hint">{model.hint}</span>
											</span>
										</span>
										{#if selectedModel === model.id}
											<span class="check-mark" aria-hidden="true">
												<Check size={14} strokeWidth={1.5} />
											</span>
										{/if}
									</button>
								{/each}
							</div>
						</div>
					{:else if flyout === 'connectors'}
						<div class="popover flyout-popover" role="menu" aria-label="Connectors">
							<label class="search-field">
								<span class="sr-only">Search connectors</span>
								<input
									{@attach attachConnectorSearchInput}
									type="search"
									bind:value={connectorQuery}
									placeholder="Search connectors..."
									autocomplete="off"
								/>
							</label>

							<div class="connectors-list" aria-live="polite" aria-busy={connectorsCache.loading}>
								{#if connectorsCache.loading && !connectorsCache.loaded}
									<p class="state-copy">Loading connectors…</p>
								{:else if connectorsCache.error && !connectorsCache.loaded}
									<div class="state-block">
										<p class="state-copy tight">Couldn’t load connectors.</p>
										<button type="button" class="retry-btn" onclick={() => connectorsCache.load(true)}>
											Retry
										</button>
									</div>
								{:else if connectorsCache.connectors.length === 0}
									<p class="state-copy">No connectors available.</p>
								{:else if filteredConnectors.length === 0}
									<p class="state-copy">No matches.</p>
								{:else}
									{#each filteredConnectors as connector (connector.id)}
										<button
											type="button"
											class="connector-row"
											class:attached={selectedConnectorIds.includes(connector.id)}
											onclick={() => toggleConnector(connector)}
										>
											<img
												class="connector-icon"
												src={connectorIconSrc(connector.type)}
												alt=""
											/>
											<span class="connector-name">{connector.name}</span>
											{#if selectedConnectorIds.includes(connector.id)}
												<span class="check-mark" aria-hidden="true">
													<Check size={14} strokeWidth={1.5} />
												</span>
											{/if}
										</button>
									{/each}
								{/if}
							</div>
						</div>
					{/if}
				</div>
			{/if}
		</div>

		<div class="toolbar-right">
			<span class="model-label" aria-label={`Model: ${selectedModelLabel}`}>{selectedModelLabel}</span>
			<button
				type="button"
				class="send-btn"
				disabled={!value.trim() || sending}
				aria-label="Send message"
				onclick={() => onsend?.()}
			>
				<ArrowUp size={15} strokeWidth={2} aria-hidden="true" />
			</button>
		</div>
	</div>
</div>

<style>
	.composer {
		display: flex;
		width: min(640px, 100%);
		flex-direction: column;
		gap: 8px;
		padding: 12px 14px 10px;
		border: 1px solid color-mix(in srgb, var(--color-line) 95%, #cfcfd4);
		border-radius: var(--radius-lg);
		background: var(--color-elevate);
		box-shadow:
			0 1px 2px rgba(15, 15, 20, 0.03),
			0 10px 28px rgba(15, 15, 20, 0.06);
	}

	.composer.docked {
		width: min(720px, 100%);
	}

	.composer:focus-within {
		border-color: color-mix(in srgb, var(--color-accent) 35%, var(--color-line));
		box-shadow:
			0 1px 2px rgba(15, 15, 20, 0.03),
			0 12px 32px rgba(15, 15, 20, 0.07),
			0 0 0 3px color-mix(in srgb, var(--color-accent) 12%, transparent);
	}

	.composer textarea {
		width: 100%;
		min-height: 22px;
		max-height: 160px;
		padding: 0 4px;
		resize: none;
		overflow-y: hidden;
		border: 0;
		outline: 0;
		color: var(--color-ink);
		background: transparent;
		font: inherit;
		font-size: 14px;
		line-height: 1.55;
	}

	.composer textarea::placeholder {
		color: #a1a1aa;
	}

	.composer-toolbar {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 10px;
	}

	.toolbar-left {
		position: relative;
		display: flex;
		min-width: 0;
		flex: 1;
		align-items: center;
		gap: 6px;
	}

	.toolbar-right {
		display: flex;
		flex-shrink: 0;
		align-items: center;
		gap: 8px;
	}

	.icon-circle,
	.send-btn,
	.menu-row,
	.retry-btn,
	.connector-row,
	.connector-dot,
	.connector-more {
		border: 0;
		font: inherit;
		cursor: pointer;
	}

	.icon-circle {
		display: inline-flex;
		flex-shrink: 0;
		align-items: center;
		justify-content: center;
		width: 28px;
		height: 28px;
		border: 1px solid transparent;
		border-radius: 999px;
		color: #a1a1aa;
		background: transparent;
	}

	.icon-circle:hover,
	.icon-circle.active {
		color: #71717a;
		background: color-mix(in srgb, var(--color-ink) 4%, transparent);
	}

	.model-label {
		display: inline-block;
		max-width: 160px;
		overflow: hidden;
		color: #a1a1aa;
		font-size: 12px;
		font-weight: 500;
		line-height: 1.2;
		text-overflow: ellipsis;
		white-space: nowrap;
		user-select: none;
		pointer-events: none;
	}

	.meta-row {
		display: inline-flex;
		min-width: 0;
		align-items: center;
	}

	.connector-stack {
		display: inline-flex;
		flex-shrink: 0;
		align-items: center;
	}

	.connector-dot {
		position: relative;
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 22px;
		height: 22px;
		margin-left: -6px;
		padding: 0;
		border-radius: 999px;
		background: color-mix(in srgb, var(--color-accent) 8%, var(--color-elevate));
		box-shadow: 0 0 0 1.5px #fff;
		transition:
			transform 0.12s ease,
			background 0.12s ease;
	}

	.connector-dot:first-child {
		margin-left: 0;
	}

	.connector-dot img {
		width: 13px;
		height: 13px;
		object-fit: contain;
	}

	.connector-dot:hover,
	.connector-dot:focus-visible,
	.connector-dot:active {
		z-index: 2;
		background: #e0e7ff;
		transform: translateY(-1px) scale(1.06);
	}

	.connector-dot:active {
		transform: translateY(0) scale(0.96);
		background: #c7d2fe;
	}

	.connector-tip {
		position: absolute;
		bottom: calc(100% + 6px);
		left: 50%;
		z-index: 5;
		padding: 3px 7px;
		border-radius: 6px;
		color: #fafafa;
		background: #27272a;
		font-size: 11px;
		font-weight: 500;
		line-height: 1.2;
		white-space: nowrap;
		pointer-events: none;
		opacity: 0;
		transform: translateX(-50%) translateY(2px);
		transition:
			opacity 0.12s ease,
			transform 0.12s ease;
	}

	.connector-dot:hover .connector-tip,
	.connector-dot:focus-visible .connector-tip,
	.connector-dot:active .connector-tip,
	.connector-more:hover .connector-tip,
	.connector-more:focus-visible .connector-tip {
		opacity: 1;
		transform: translateX(-50%) translateY(0);
	}

	.connector-more {
		position: relative;
		margin-left: 4px;
		padding: 0 2px;
		color: #a1a1aa;
		background: transparent;
		font-size: 11px;
		font-weight: 600;
	}

	.connector-more:hover:not(:disabled) {
		color: #71717a;
	}

	.connector-more:disabled {
		cursor: default;
	}

	@media (prefers-reduced-motion: reduce) {
		.connector-dot {
			transition: none;
		}

		.connector-tip {
			transition: none;
		}
	}

	.menu-shell {
		position: absolute;
		bottom: calc(100% + 8px);
		left: 0;
		z-index: 20;
	}

	.popover {
		overflow: hidden;
		border: 1px solid color-mix(in srgb, var(--color-line) 90%, #d4d4d8);
		border-radius: 12px;
		background: var(--color-elevate);
		box-shadow:
			0 1px 2px rgba(15, 15, 20, 0.04),
			0 14px 32px rgba(15, 15, 20, 0.1);
	}

	.root-popover {
		position: relative;
		width: min(240px, calc(100vw - 32px));
	}

	.flyout-popover {
		position: absolute;
		bottom: 0;
		left: calc(100% + 4px);
		width: min(272px, calc(100vw - 32px));
		animation: flyout-in 120ms ease;
	}

	@keyframes flyout-in {
		from {
			opacity: 0;
			transform: translateX(-4px);
		}
		to {
			opacity: 1;
			transform: translateX(0);
		}
	}

	.search-field {
		display: block;
		padding: 6px 6px 4px;
	}

	.search-field input {
		width: 100%;
		padding: 6px 8px;
		border: 0;
		border-radius: 7px;
		color: var(--color-ink);
		background: var(--color-fill);
		font: inherit;
		font-size: 12px;
		outline: 0;
	}

	.search-field input::placeholder {
		color: #a1a1aa;
	}

	.search-field input:focus {
		background: var(--color-sidebar);
	}

	.menu-section {
		display: flex;
		flex-direction: column;
		padding: 2px;
	}

	.models-list {
		max-height: 240px;
		overflow-y: auto;
		padding-bottom: 4px;
	}

	.menu-row {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 8px;
		width: 100%;
		padding: 6px 8px;
		border-radius: 7px;
		color: var(--color-text-strong);
		background: transparent;
		font-size: 12.5px;
		text-align: left;
	}

	.menu-row:hover,
	.menu-row.flyout-open,
	.menu-row.selected,
	.model-row:hover {
		background: var(--color-fill);
	}

	.menu-row-main {
		display: inline-flex;
		min-width: 0;
		align-items: center;
		gap: 8px;
	}

	.menu-row-main.column {
		flex-direction: column;
		align-items: flex-start;
		gap: 1px;
	}

	.model-row-main {
		display: inline-flex;
		min-width: 0;
		align-items: center;
		gap: 8px;
	}

	.model-logo {
		width: 16px;
		height: 16px;
		flex-shrink: 0;
		object-fit: contain;
		border-radius: 3px;
	}

	.menu-icon {
		display: inline-flex;
		width: 14px;
		height: 14px;
		flex-shrink: 0;
		align-items: center;
		justify-content: center;
		color: #71717a;
	}

	.menu-meta {
		display: inline-flex;
		min-width: 0;
		align-items: center;
		gap: 6px;
	}

	.menu-hint {
		overflow: hidden;
		max-width: 90px;
		color: var(--color-muted);
		font-size: 10.5px;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.badge {
		display: inline-flex;
		min-width: 18px;
		align-items: center;
		justify-content: center;
		padding: 1px 6px;
		border-radius: 999px;
		color: var(--color-text-2);
		background: var(--color-sidebar);
		font-size: 11px;
		font-weight: 600;
	}

	.menu-meta :global(.chevron) {
		flex-shrink: 0;
		color: #a1a1aa;
	}

	.model-title {
		overflow: hidden;
		color: var(--color-text-strong);
		font-size: 12.5px;
		font-weight: 600;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.model-hint {
		overflow: hidden;
		color: var(--color-muted);
		font-size: 11px;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.connectors-list {
		display: flex;
		max-height: 220px;
		flex-direction: column;
		gap: 1px;
		overflow-y: auto;
		padding: 2px 2px 6px;
	}

	.connector-row {
		display: flex;
		align-items: center;
		gap: 8px;
		width: 100%;
		padding: 7px 8px;
		border-radius: 7px;
		color: inherit;
		background: transparent;
		text-align: left;
	}

	.connector-row:hover,
	.connector-row.attached {
		background: var(--color-fill);
	}

	.connector-icon {
		width: 16px;
		height: 16px;
		flex-shrink: 0;
		object-fit: contain;
	}

	.connector-name {
		min-width: 0;
		flex: 1;
		overflow: hidden;
		color: var(--color-text-strong);
		font-size: 12.5px;
		font-weight: 500;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.check-mark {
		display: inline-flex;
		flex-shrink: 0;
		align-items: center;
		justify-content: center;
		color: var(--color-text-3);
	}

	.state-block {
		display: flex;
		flex-direction: column;
		align-items: flex-start;
		gap: 6px;
		padding: 6px 8px;
	}

	.state-copy {
		margin: 0;
		padding: 8px;
		color: var(--color-muted);
		font-size: 11.5px;
		line-height: 1.35;
	}

	.state-copy.tight,
	.state-block .state-copy {
		padding: 0;
	}

	.retry-btn {
		padding: 5px 10px;
		border-radius: 8px;
		color: var(--color-accent);
		background: color-mix(in srgb, var(--color-accent) 8%, var(--color-elevate));
		font-size: 12px;
		font-weight: 500;
	}

	.retry-btn:hover {
		background: color-mix(in srgb, var(--color-accent) 14%, var(--color-elevate));
	}

	.send-btn {
		display: inline-flex;
		flex-shrink: 0;
		align-items: center;
		justify-content: center;
		width: 32px;
		height: 32px;
		border-radius: 999px;
		color: #fff;
		background: #171717;
		transition:
			opacity 120ms ease,
			transform 120ms ease;
	}

	.send-btn:hover:not(:disabled) {
		transform: translateY(-1px);
	}

	.send-btn:disabled {
		cursor: not-allowed;
		opacity: 0.35;
	}

	.sr-only {
		position: absolute;
		width: 1px;
		height: 1px;
		padding: 0;
		margin: -1px;
		overflow: hidden;
		clip: rect(0, 0, 0, 0);
		white-space: nowrap;
		border: 0;
	}

	@media (max-width: 560px) {
		.model-label {
			max-width: 110px;
		}

		.flyout-popover {
			left: 0;
			bottom: calc(100% + 4px);
			width: min(240px, calc(100vw - 32px));
		}
	}

	@media (prefers-reduced-motion: reduce) {
		.send-btn {
			transition: none;
		}

		.flyout-popover {
			animation: none;
		}
	}
</style>

// examples/python-react-demo/frontend/src/components/Composer.tsx
import { ArrowUp, Boxes, Cable, Check, ChevronRight, Plus, X } from 'lucide-react';
import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';

import { CHAT_MODELS, DEFAULT_CHAT_MODEL } from '../lib/chatModels';
import { connectorIconSrc } from '../lib/connectorIcons';
import { connectorsCache, useConnectors } from '../lib/connectorsCache';
import { cx } from '../lib/cx';
import { useDismissable } from '../lib/useDismissable';

type Flyout = 'models' | 'connectors';

type Props = {
	value?: string;
	sending?: boolean;
	docked?: boolean;
	/** When true, model + connectors are read-only (existing chat). */
	configLocked?: boolean;
	selectedConnectorIds?: number[];
	selectedModel?: string;
	onValueChange?: (value: string) => void;
	onConnectorIdsChange?: (ids: number[]) => void;
	onModelChange?: (model: string) => void;
	onSend?: () => void;
	className?: string;
};

const ROOT_ITEMS = [
	{ id: 'models' as const, label: 'Models', Icon: Boxes },
	{ id: 'connectors' as const, label: 'Connectors', Icon: Cable }
];

const TEXTAREA_MAX_PX = 160;

const POPOVER =
	'overflow-hidden rounded-[12px] border border-[color-mix(in_srgb,var(--color-line)_90%,#d4d4d8)] bg-elevate shadow-[0_1px_2px_rgba(15,15,20,0.04),0_14px_32px_rgba(15,15,20,0.1)]';
const MENU_SECTION = 'flex flex-col p-0.5';
const MENU_ROW =
	'flex w-full items-center justify-between gap-2 rounded-[7px] px-2 py-1.5 text-left text-[12.5px] text-text-strong';
/** `flex-direction`/`gap` are set per variant so the two never collide. */
const MENU_ROW_MAIN = 'inline-flex min-w-0';
const CHECK_MARK = 'inline-flex shrink-0 items-center justify-center text-text-3';
const STATE_COPY = 'm-0 text-[11.5px] leading-[1.35] text-muted';

export function Composer({
	value = '',
	sending = false,
	docked = false,
	configLocked = false,
	selectedConnectorIds = [],
	selectedModel = DEFAULT_CHAT_MODEL as string,
	onValueChange,
	onConnectorIdsChange,
	onModelChange,
	onSend,
	className = ''
}: Props) {
	const connectors = useConnectors();
	const [menuOpen, setMenuOpen] = useState(false);
	const [flyout, setFlyout] = useState<Flyout | null>(null);
	const [connectorQuery, setConnectorQuery] = useState('');
	const menuRootRef = useRef<HTMLDivElement | null>(null);
	const textareaRef = useRef<HTMLTextAreaElement | null>(null);
	const searchRef = useRef<HTMLInputElement | null>(null);

	const normalizedConnectorQuery = connectorQuery.trim().toLowerCase();

	const filteredConnectors = connectors.connectors.filter((connector) => {
		if (!normalizedConnectorQuery) return true;
		return (
			connector.name.toLowerCase().includes(normalizedConnectorQuery) ||
			connector.type.toLowerCase().includes(normalizedConnectorQuery)
		);
	});

	const selectedModelLabel =
		CHAT_MODELS.find((model) => model.id === selectedModel)?.label ??
		selectedModel.replace(/^MODEL_/, '').replaceAll('_', ' ');

	const selectedChips = selectedConnectorIds.map((id) => {
		const match = connectors.connectors.find((connector) => connector.id === id);
		return {
			id,
			name: match?.name ?? `Connector ${id}`,
			type: match?.type ?? 'UNKNOWN'
		};
	});

	const closeMenu = useCallback(() => {
		setMenuOpen(false);
		setFlyout(null);
		setConnectorQuery('');
	}, []);

	function openMenu(initialFlyout: Flyout | null = null) {
		if (configLocked) return;
		setMenuOpen(true);
		setFlyout(initialFlyout);
		setConnectorQuery('');
		if (initialFlyout === 'connectors') void connectorsCache.load();
	}

	function toggleMenu() {
		if (configLocked) return;
		if (menuOpen) {
			closeMenu();
			return;
		}
		openMenu();
	}

	function openFlyout(next: Flyout) {
		if (configLocked) return;
		if (flyout === next) return;
		setFlyout(next);
		setConnectorQuery('');
		if (next === 'connectors') void connectorsCache.load();
	}

	function selectModel(modelId: string) {
		if (configLocked) return;
		onModelChange?.(modelId);
		closeMenu();
		textareaRef.current?.focus();
	}

	function toggleConnector(connector: { id: number }) {
		if (configLocked) return;
		if (selectedConnectorIds.includes(connector.id)) {
			onConnectorIdsChange?.(selectedConnectorIds.filter((id) => id !== connector.id));
		} else {
			onConnectorIdsChange?.([...selectedConnectorIds, connector.id]);
		}
	}

	function removeConnector(id: number) {
		if (configLocked) return;
		onConnectorIdsChange?.(selectedConnectorIds.filter((selectedId) => selectedId !== id));
	}

	const resizeTextarea = useCallback(() => {
		const el = textareaRef.current;
		if (!el) return;
		el.style.height = '0px';
		const next = Math.min(el.scrollHeight, TEXTAREA_MAX_PX);
		el.style.height = `${next}px`;
		el.style.overflowY = el.scrollHeight > TEXTAREA_MAX_PX ? 'auto' : 'hidden';
	}, []);

	useLayoutEffect(() => {
		resizeTextarea();
	}, [value, resizeTextarea]);

	function insertNewline() {
		const el = textareaRef.current;
		if (!el) return;
		const start = el.selectionStart;
		const end = el.selectionEnd;
		onValueChange?.(`${value.slice(0, start)}\n${value.slice(end)}`);
		queueMicrotask(() => {
			el.selectionStart = el.selectionEnd = start + 1;
			resizeTextarea();
			el.focus();
		});
	}

	function handleComposerKeydown(event: React.KeyboardEvent<HTMLTextAreaElement>) {
		if (event.key !== 'Enter') return;

		// Cmd/Ctrl+Enter or Shift+Enter → new line (grows until max, then scrolls).
		if (event.metaKey || event.ctrlKey || event.shiftKey) {
			event.preventDefault();
			insertNewline();
			return;
		}

		event.preventDefault();
		onSend?.();
	}

	useDismissable(menuOpen, closeMenu, {
		contains: (target) => target instanceof Node && menuRootRef.current?.contains(target) === true,
		// Escape backs out of an open flyout first, and only then closes the menu.
		onEscape: (event) => {
			event.preventDefault();
			if (!flyout) return false;
			setFlyout(null);
			setConnectorQuery('');
			return true;
		}
	});

	useEffect(() => {
		if (flyout === 'connectors') queueMicrotask(() => searchRef.current?.focus());
	}, [flyout]);

	return (
		// `composer-shell` stays unhashed so ChatPage's dock can centre it via :global().
		<div className={cx(
				'composer-shell flex flex-col gap-2',
				docked ? 'w-[min(720px,100%)]' : 'w-[min(640px,100%)]',
				className
			)}>
			<div className="flex w-full flex-col gap-2 rounded-lg border border-[color-mix(in_srgb,var(--color-line)_95%,#cfcfd4)] bg-elevate px-3.5 pt-3 pb-2.5 shadow-[0_1px_2px_rgba(15,15,20,0.03),0_10px_28px_rgba(15,15,20,0.06)] focus-within:border-[color-mix(in_srgb,var(--color-accent)_35%,var(--color-line))] focus-within:shadow-[0_1px_2px_rgba(15,15,20,0.03),0_12px_32px_rgba(15,15,20,0.07),0_0_0_3px_color-mix(in_srgb,var(--color-accent)_12%,transparent)]">
				<textarea
					ref={textareaRef}
					className="max-h-40 min-h-[22px] w-full resize-none overflow-y-hidden border-0 bg-transparent px-1 py-0 text-[14px] leading-[1.55] text-ink outline-0 placeholder:text-[#a1a1aa]"
					value={value}
					onChange={(event) => onValueChange?.(event.target.value)}
					onKeyDown={handleComposerKeydown}
					rows={1}
					placeholder="Plan, @ for context, / for commands"
					aria-label="Message"
				/>

				<div className="flex items-center justify-between gap-2.5">
					<div className="relative flex min-w-0 flex-1 items-center gap-1.5" ref={menuRootRef}>
						{!configLocked && (
							<button
								type="button"
								className={cx(
									'inline-flex size-7 shrink-0 cursor-pointer items-center justify-center rounded-full border border-transparent',
									menuOpen || selectedConnectorIds.length > 0
										? 'bg-ink/4 text-[#71717a]'
										: 'bg-transparent text-[#a1a1aa] hover:bg-ink/4 hover:text-[#71717a]'
								)}
								aria-label="Composer settings"
								aria-haspopup="menu"
								aria-expanded={menuOpen}
								onClick={toggleMenu}
							>
								<Plus size={15} strokeWidth={1.5} aria-hidden="true" />
							</button>
						)}

						{menuOpen && !configLocked && (
							<div className="absolute bottom-[calc(100%+8px)] left-0 z-20">
								<div
									className={cx(POPOVER, 'relative w-[min(240px,calc(100vw-32px))]')}
									role="menu"
									aria-label="Composer settings"
								>
									<div className={MENU_SECTION}>
										{ROOT_ITEMS.map((item) => (
											<button
												key={item.id}
												type="button"
												className={cx(MENU_ROW, flyout === item.id ? 'bg-fill' : 'bg-transparent hover:bg-fill')}
												role="menuitem"
												aria-haspopup="menu"
												aria-expanded={flyout === item.id}
												onMouseEnter={() => openFlyout(item.id)}
												onFocus={() => openFlyout(item.id)}
												onClick={() => openFlyout(item.id)}
											>
												<span className={cx(MENU_ROW_MAIN, 'items-center gap-2')}>
													<span className="inline-flex size-3.5 shrink-0 items-center justify-center text-[#71717a]" aria-hidden="true">
														<item.Icon size={14} strokeWidth={1.5} />
													</span>
													{item.label}
												</span>
												<span className="inline-flex min-w-0 items-center gap-1.5">
													{item.id === 'connectors' && selectedConnectorIds.length > 0 ? (
														<span className="inline-flex min-w-[18px] items-center justify-center rounded-full bg-sidebar px-1.5 py-px text-[11px] font-semibold text-text-2">{selectedConnectorIds.length}</span>
													) : item.id === 'models' ? (
														<span className="max-w-[90px] overflow-hidden text-[10.5px] text-ellipsis whitespace-nowrap text-muted">{selectedModelLabel}</span>
													) : null}
													<ChevronRight
														className="shrink-0 text-[#a1a1aa]"
														size={14}
														strokeWidth={1.5}
														aria-hidden="true"
													/>
												</span>
											</button>
										))}
									</div>
								</div>

								{flyout === 'models' && (
									<div
										className={cx(
										POPOVER,
										'absolute bottom-0 left-[calc(100%+4px)] w-[min(272px,calc(100vw-32px))] animate-flyout-in motion-reduce:animate-none',
										'max-[560px]:bottom-[calc(100%+4px)] max-[560px]:left-0 max-[560px]:w-[min(240px,calc(100vw-32px))]'
									)}
										role="menu"
										aria-label="Models"
									>
										<div className={cx(MENU_SECTION, 'max-h-60 overflow-y-auto pb-1')}>
											{CHAT_MODELS.map((model) => (
												<button
													key={model.id}
													type="button"
													className={cx(
														MENU_ROW,
												selectedModel === model.id ? 'bg-fill' : 'bg-transparent hover:bg-fill'
													)}
													role="menuitem"
													onClick={() => selectModel(model.id)}
												>
													<span className="inline-flex min-w-0 items-center gap-2">
														<img
															className="size-4 shrink-0 rounded-[3px] object-contain"
															src={connectorIconSrc(model.provider)}
															alt=""
														/>
														<span className={cx(MENU_ROW_MAIN, 'flex-col items-start gap-px')}>
															<span className="overflow-hidden text-[12.5px] font-semibold text-ellipsis whitespace-nowrap text-text-strong">{model.label}</span>
															<span className="overflow-hidden text-[11px] text-ellipsis whitespace-nowrap text-muted">{model.hint}</span>
														</span>
													</span>
													{selectedModel === model.id && (
														<span className={CHECK_MARK} aria-hidden="true">
															<Check size={14} strokeWidth={1.5} />
														</span>
													)}
												</button>
											))}
										</div>
									</div>
								)}

								{flyout === 'connectors' && (
									<div
										className={cx(
										POPOVER,
										'absolute bottom-0 left-[calc(100%+4px)] w-[min(272px,calc(100vw-32px))] animate-flyout-in motion-reduce:animate-none',
										'max-[560px]:bottom-[calc(100%+4px)] max-[560px]:left-0 max-[560px]:w-[min(240px,calc(100vw-32px))]'
									)}
										role="menu"
										aria-label="Connectors"
									>
										<label className="block px-1.5 pt-1.5 pb-1">
											<span className="sr-only">Search connectors</span>
											<input
												ref={searchRef}
												className="w-full rounded-[7px] border-0 bg-fill px-2 py-1.5 text-[12px] text-ink outline-0 placeholder:text-[#a1a1aa] focus:bg-sidebar"
												type="search"
												value={connectorQuery}
												onChange={(event) => setConnectorQuery(event.target.value)}
												placeholder="Search connectors..."
												autoComplete="off"
											/>
										</label>

										<div
											className="flex max-h-[220px] flex-col gap-px overflow-y-auto px-0.5 pt-0.5 pb-1.5"
											aria-live="polite"
											aria-busy={connectors.loading}
										>
											{connectors.loading && !connectors.loaded ? (
												<p className={cx(STATE_COPY, 'p-2')}>Loading connectors…</p>
											) : connectors.error && !connectors.loaded ? (
												<div className="flex flex-col items-start gap-1.5 px-2 py-1.5">
													<p className={STATE_COPY}>
														Couldn’t load connectors.
													</p>
													<button
														type="button"
														className="rounded-[8px] bg-[color-mix(in_srgb,var(--color-accent)_8%,var(--color-elevate))] px-2.5 py-[5px] text-[12px] font-medium text-accent hover:bg-[color-mix(in_srgb,var(--color-accent)_14%,var(--color-elevate))]"
														onClick={() => connectorsCache.load(true)}
													>
														Retry
													</button>
												</div>
											) : connectors.connectors.length === 0 ? (
												<p className={cx(STATE_COPY, 'p-2')}>No connectors available.</p>
											) : filteredConnectors.length === 0 ? (
												<p className={cx(STATE_COPY, 'p-2')}>No matches.</p>
											) : (
												filteredConnectors.map((connector) => (
													<button
														key={connector.id}
														type="button"
														className={cx(
															'flex w-full items-center gap-2 rounded-[7px] px-2 py-[7px] text-left text-inherit',
														selectedConnectorIds.includes(connector.id)
															? 'bg-fill'
															: 'bg-transparent hover:bg-fill'
														)}
														onClick={() => toggleConnector(connector)}
													>
														<img
															className="size-4 shrink-0 object-contain"
															src={connectorIconSrc(connector.type)}
															alt=""
														/>
														<span className="min-w-0 flex-1 overflow-hidden text-[12.5px] font-medium text-ellipsis whitespace-nowrap text-text-strong">{connector.name}</span>
														{selectedConnectorIds.includes(connector.id) && (
															<span className={CHECK_MARK} aria-hidden="true">
																<Check size={14} strokeWidth={1.5} />
															</span>
														)}
													</button>
												))
											)}
										</div>
									</div>
								)}
							</div>
						)}
					</div>

					<div className="flex shrink-0 items-center gap-2">
						<span className="pointer-events-none inline-block max-w-40 overflow-hidden text-[12px] leading-[1.2] font-medium text-ellipsis whitespace-nowrap text-[#a1a1aa] select-none max-[560px]:max-w-[110px]" aria-label={`Model: ${selectedModelLabel}`}>
							{selectedModelLabel}
						</span>
						<button
							type="button"
							className="inline-flex size-8 shrink-0 items-center justify-center rounded-full bg-[#171717] text-white transition-[opacity,transform] duration-[120ms] hover:not-disabled:-translate-y-px disabled:cursor-not-allowed disabled:opacity-35 motion-reduce:transition-none"
							disabled={!value.trim() || sending}
							aria-label="Send message"
							onClick={() => onSend?.()}
						>
							<ArrowUp size={15} strokeWidth={2} aria-hidden="true" />
						</button>
					</div>
				</div>
			</div>

			{selectedChips.length > 0 && (
				<div className="flex flex-wrap items-center gap-1.5 px-1" aria-label="Attached connectors">
					{selectedChips.map((chip) => (
						<span key={chip.id} className={cx(
								'inline-flex max-w-full items-center gap-1.5 rounded-[7px] border border-line bg-sidebar py-[3px] pl-[7px] text-[12px] leading-[1.2] font-medium text-text-strong [&_img]:size-3.5 [&_img]:shrink-0 [&_img]:object-contain',
								configLocked ? 'pr-[9px]' : 'pr-[5px]'
							)}>
							<img src={connectorIconSrc(chip.type)} alt="" />
							<span className="max-w-[180px] overflow-hidden text-ellipsis whitespace-nowrap">{chip.name}</span>
							{!configLocked && (
								<button
									type="button"
									className="inline-flex size-4 shrink-0 cursor-pointer items-center justify-center rounded-full bg-transparent p-0 text-[#a1a1aa] hover:bg-ink/8 hover:text-[#52525b] focus-visible:bg-ink/8 focus-visible:text-[#52525b]"
									aria-label={`Remove ${chip.name}`}
									onClick={() => removeConnector(chip.id)}
								>
									<X size={12} strokeWidth={2} aria-hidden="true" />
								</button>
							)}
						</span>
					))}
				</div>
			)}
		</div>
	);
}
