// examples/svelte-demo/src/lib/primitives/FilterToolbar/DateRangeFilter.svelte
<script lang="ts">
  import Check from "@lucide/svelte/icons/check";

  type Preset = { value: string; label: string };

  let {
    presets,
    isPresetSelected,
    onSelectPreset,
    isAllTime = false,
    onSelectAllTime,
    sinceValue,
    maxValue,
    onSelectSince,
  }: {
    presets: Preset[];
    isPresetSelected: (value: string) => boolean;
    onSelectPreset: (value: string) => void;
    /** No date facet value selected — the default, "All time". */
    isAllTime?: boolean;
    onSelectAllTime: () => void;
    /** `YYYY-MM-DD` when a custom since-date is active. */
    sinceValue?: string;
    /** `YYYY-MM-DD` upper bound — a since-date in the future selects nothing. */
    maxValue: string;
    onSelectSince: (date: string | undefined) => void;
  } = $props();
</script>

<button type="button" class="row" onclick={onSelectAllTime}>
  <span class="check" class:on={isAllTime}>
    {#if isAllTime}<Check size={11} strokeWidth={3} />{/if}
  </span>
  <span class="row-label">All time</span>
</button>

{#each presets as preset (preset.value)}
  {@const on = isPresetSelected(preset.value)}
  <button type="button" class="row" onclick={() => onSelectPreset(preset.value)}>
    <span class="check" class:on>
      {#if on}<Check size={11} strokeWidth={3} />{/if}
    </span>
    <span class="row-label">{preset.label}</span>
  </button>
{/each}

<!-- A *since* date, not a range — the same shape demo2's feed date filter uses.
     There is deliberately no end-date control. -->
<div class="since">
  <label class="since-label" for="filter-since">Since</label>
  <input
    id="filter-since"
    type="date"
    class="since-input"
    max={maxValue}
    value={sinceValue ?? ""}
    onchange={(event) => onSelectSince(event.currentTarget.value || undefined)}
  />
</div>

<style>
  .row {
    display: flex;
    align-items: center;
    gap: 8px;
    width: 100%;
    padding: 6px 8px;
    border: 0;
    border-radius: 5px;
    background: transparent;
    color: var(--color-text-3);
    font: inherit;
    font-size: 12px;
    text-align: left;
    cursor: pointer;
  }

  .row:hover {
    background: color-mix(in srgb, var(--color-elevate) 70%, transparent);
  }

  .check {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    width: 14px;
    height: 14px;
    border: 1px solid color-mix(in srgb, var(--color-line) 90%, transparent);
    border-radius: 4px;
    color: var(--color-paper);
  }

  .check.on {
    border-color: var(--color-accent);
    background: var(--color-accent);
  }

  .row-label {
    min-width: 0;
    flex: 1;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .since {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: 4px;
    padding: 8px 8px 2px;
    border-top: 1px solid color-mix(in srgb, var(--color-line) 55%, transparent);
  }

  .since-label {
    color: var(--color-muted);
    font-size: 11px;
  }

  .since-input {
    min-width: 0;
    flex: 1;
    padding: 4px 6px;
    border: 1px solid color-mix(in srgb, var(--color-line) 85%, transparent);
    border-radius: 5px;
    background: var(--color-paper);
    color: var(--color-ink);
    font: inherit;
    font-size: 11.5px;
  }
</style>

// examples/python-react-demo/frontend/src/components/filterToolbar/DateRangeFilter.tsx
import { Check } from 'lucide-react';

import { FACET_CHECK, FACET_CHECK_ON, FACET_ROW, FACET_ROW_LABEL } from './styles';

type Preset = { value: string; label: string };

type Props = {
	presets: Preset[];
	isPresetSelected: (value: string) => boolean;
	onSelectPreset: (value: string) => void;
	/** No date facet value selected — the default, "All time". */
	isAllTime?: boolean;
	onSelectAllTime: () => void;
	/** `YYYY-MM-DD` when a custom since-date is active. */
	sinceValue?: string;
	/** `YYYY-MM-DD` upper bound — a since-date in the future selects nothing. */
	maxValue: string;
	onSelectSince: (date: string | undefined) => void;
};

export function DateRangeFilter({
	presets,
	isPresetSelected,
	onSelectPreset,
	isAllTime = false,
	onSelectAllTime,
	sinceValue,
	maxValue,
	onSelectSince
}: Props) {
	return (
		<>
			<button type="button" className={FACET_ROW} onClick={onSelectAllTime}>
				<span className={isAllTime ? FACET_CHECK_ON : FACET_CHECK}>
					{isAllTime && <Check size={11} strokeWidth={3} />}
				</span>
				<span className={FACET_ROW_LABEL}>All time</span>
			</button>

			{presets.map((preset) => {
				const on = isPresetSelected(preset.value);
				return (
					<button
						key={preset.value}
						type="button"
						className={FACET_ROW}
						onClick={() => onSelectPreset(preset.value)}
					>
						<span className={on ? FACET_CHECK_ON : FACET_CHECK}>
							{on && <Check size={11} strokeWidth={3} />}
						</span>
						<span className={FACET_ROW_LABEL}>{preset.label}</span>
					</button>
				);
			})}

			{/* A *since* date, not a range — the same shape demo2's feed date filter
			    uses. There is deliberately no end-date control. */}
			<div className="mt-1 flex items-center gap-2 border-t border-line/55 px-2 pt-2 pb-0.5">
				<label className="text-[11px] text-muted" htmlFor="filter-since">
					Since
				</label>
				<input
					id="filter-since"
					type="date"
					className="min-w-0 flex-1 rounded-md border border-line/85 bg-paper px-1.5 py-1 text-[11.5px] text-ink"
					max={maxValue}
					value={sinceValue ?? ''}
					onChange={(event) => onSelectSince(event.currentTarget.value || undefined)}
				/>
			</div>
		</>
	);
}
