// examples/python-react-demo/frontend/src/primitives/Tooltip.tsx
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';

import { cx } from '../lib/cx';

type Side = 'top' | 'bottom' | 'left' | 'right';

type Props = {
	label: string;
	shortcut?: string;
	side?: Side;
	children: ReactNode;
};

const GAP = 6;

/**
 * Centering rides on the `translate` property so the reveal keyframe owns
 * `transform`; the two compose cleanly. `--tooltip-dx/dy` feed the keyframe.
 */
const SIDE_CLASS: Record<Side, string> = {
	bottom: '-translate-x-1/2 [--tooltip-dx:0px] [--tooltip-dy:-5px]',
	top: '-translate-x-1/2 -translate-y-full [--tooltip-dx:0px] [--tooltip-dy:5px]',
	right: '-translate-y-1/2 [--tooltip-dx:-5px] [--tooltip-dy:0px]',
	left: '-translate-x-full -translate-y-1/2 [--tooltip-dx:5px] [--tooltip-dy:0px]'
};

export function Tooltip({ label, shortcut, side = 'bottom', children }: Props) {
	const wrapRef = useRef<HTMLSpanElement | null>(null);
	const timerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
	const [open, setOpen] = useState(false);
	const [point, setPoint] = useState({ x: 0, y: 0 });

	useEffect(() => () => clearTimeout(timerRef.current), []);

	function show() {
		const wrap = wrapRef.current;
		const el = wrap?.firstElementChild ?? wrap;
		if (!el) return;
		const r = el.getBoundingClientRect();
		if (side === 'bottom') setPoint({ x: r.left + r.width / 2, y: r.bottom + GAP });
		else if (side === 'top') setPoint({ x: r.left + r.width / 2, y: r.top - GAP });
		else if (side === 'right') setPoint({ x: r.right + GAP, y: r.top + r.height / 2 });
		else setPoint({ x: r.left - GAP, y: r.top + r.height / 2 });
		clearTimeout(timerRef.current);
		timerRef.current = setTimeout(() => setOpen(true), 300);
	}

	function hide() {
		clearTimeout(timerRef.current);
		setOpen(false);
	}

	return (
		<>
			<span
				className="inline-flex"
				ref={wrapRef}
				onPointerEnter={show}
				onPointerLeave={hide}
				onFocus={show}
				onBlur={hide}
			>
				{children}
			</span>

			{open &&
				createPortal(
					<span
						className={cx(
							'pointer-events-none fixed z-[1000] inline-flex animate-tooltip-reveal items-center gap-[0.35rem] rounded-xs bg-ink px-[0.45rem] py-[0.22rem] text-[11.5px] leading-[1.2] whitespace-nowrap text-paper shadow-[0_4px_12px_rgb(0_0_0/0.16)] [will-change:transform,opacity] motion-reduce:animate-none motion-reduce:[will-change:auto]',
							SIDE_CLASS[side]
						)}
						role="tooltip"
						style={{ left: `${point.x}px`, top: `${point.y}px` }}
					>
						{label}
						{shortcut && (
							<kbd className="rounded-[4px] bg-paper/22 px-[0.28rem] py-[0.02rem] font-[inherit] text-[10.5px] text-paper">
								{shortcut}
							</kbd>
						)}
					</span>,
					document.body
				)}
		</>
	);
}

// examples/chat-demo/src/lib/primitives/Tooltip/Tooltip.svelte
<script lang="ts">
	import type { Snippet } from "svelte";

	type Side = "top" | "bottom" | "left" | "right";

	interface Props {
		label: string;
		shortcut?: string;
		side?: Side;
		children: Snippet;
	}

	let { label, shortcut, side = "bottom", children }: Props = $props();

	const GAP = 6;
	let wrap = $state<HTMLElement>();
	let open = $state(false);
	let x = $state(0);
	let y = $state(0);
	let timer: ReturnType<typeof setTimeout> | undefined;

	function show() {
		const el = wrap?.firstElementChild ?? wrap;
		if (!el) return;
		const r = el.getBoundingClientRect();
		if (side === "bottom") (x = r.left + r.width / 2), (y = r.bottom + GAP);
		else if (side === "top") (x = r.left + r.width / 2), (y = r.top - GAP);
		else if (side === "right")
			(x = r.right + GAP), (y = r.top + r.height / 2);
		else (x = r.left - GAP), (y = r.top + r.height / 2);
		clearTimeout(timer);
		timer = setTimeout(() => (open = true), 300);
	}
	function hide() {
		clearTimeout(timer);
		open = false;
	}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<span
	class="tooltip-wrap"
	bind:this={wrap}
	onpointerenter={show}
	onpointerleave={hide}
	onfocusin={show}
	onfocusout={hide}
>
	{@render children()}
</span>

{#if open}
	<span
		class="tooltip {side}"
		role="tooltip"
		style="left: {x}px; top: {y}px;"
	>
		{label}
		{#if shortcut}<kbd>{shortcut}</kbd>{/if}
	</span>
{/if}

<style>
	.tooltip-wrap {
		display: inline-flex;
	}
	.tooltip {
		position: fixed;
		z-index: 1000;
		display: inline-flex;
		align-items: center;
		gap: 0.35rem;
		white-space: nowrap;
		pointer-events: none;
		padding: 0.22rem 0.45rem;
		font-size: 11.5px;
		line-height: 1.2;
		color: var(--color-paper);
		background: var(--color-ink);
		border-radius: var(--radius-xs, 6px);
		box-shadow: 0 4px 12px rgb(0 0 0 / 0.16);
	}
	/* Anchor point is the measured (x, y); shift the bubble onto the right side. */
	.tooltip.bottom {
		transform: translateX(-50%);
	}
	.tooltip.top {
		transform: translate(-50%, -100%);
	}
	.tooltip.right {
		transform: translateY(-50%);
	}
	.tooltip.left {
		transform: translate(-100%, -50%);
	}
	kbd {
		font: inherit;
		font-size: 10.5px;
		padding: 0.02rem 0.28rem;
		border-radius: 4px;
		background: color-mix(in srgb, var(--color-paper) 22%, transparent);
		color: var(--color-paper);
	}
</style>
