// examples/svelte-demo/src/lib/components/AgentsPage.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { resolve } from "$app/paths";
	import AgentIdenticon from "$lib/components/AgentIdenticon.svelte";
	import UnicodeSpinner from "$lib/components/UnicodeSpinner.svelte";
	import { formatCron } from "$lib/cron";
	import { FilterToolbar, Page } from "$lib/primitives";
	import type { FilterField } from "$lib/primitives";
	import { applyFilters, type ColumnFilter, type FilterableColumn } from "$lib/tableFilter";
	import { applySort, type SortEntry, type SortableColumn } from "$lib/tableSort";
	import { isRecord } from "$lib/utils";

	type AgentListItem = {
		id: string;
		name: string;
		prompt: string;
		isActive: boolean;
		profileImageUrl: string | null;
		ownerName: string | null;
		llmModel: string | null;
		schedules: string[];
		lastPostAt: string | null;
	};

	type AgentGroup = {
		key: "active" | "inactive";
		title: string;
		hint: string;
		agents: AgentListItem[];
	};

	let agents = $state<AgentListItem[]>([]);
	let loading = $state(true);
	let error = $state(false);

	let search = $state("");
	let filters = $state<ColumnFilter[]>([]);
	let sortEntries = $state<SortEntry[]>([{ columnId: "lastPost", dir: "desc" }]);

	// ListAgents takes no search/sort/paging params, so this surface filters
	// client-side: facet options come from the loaded rows via `items`.
	const fields: FilterField<AgentListItem>[] = [
		{
			id: "lastPost",
			header: "Last post",
			sortable: true,
			sortType: "date",
			sortValue: (agent) => (agent.lastPostAt ? new Date(agent.lastPostAt) : null),
		},
		{ id: "name", header: "Name", sortable: true, sortType: "text" },
		{
			id: "status",
			header: "Status",
			filterable: true,
			filterValue: (agent) => (agent.isActive ? "Active" : "Inactive"),
		},
		{
			id: "ownerName",
			header: "Owner",
			filterable: true,
			filterKind: "people",
			filterValue: (agent) => agent.ownerName ?? "",
		},
		{
			id: "llmModel",
			header: "Model",
			filterable: true,
			filterValue: (agent) => agent.llmModel ?? "",
		},
		{
			id: "schedule",
			header: "Schedule",
			filterable: true,
			filterValue: (agent) => (agent.schedules.length ? "Scheduled" : "No schedule"),
		},
	];

	const fieldMap = $derived(
		new Map(fields.map((field) => [field.id, field])) as Map<
			string,
			FilterableColumn<AgentListItem> & SortableColumn<AgentListItem>
		>,
	);

	const narrowed = $derived(filters.length > 0 || search.trim().length > 0);

	/** Search matches name, prompt and owner; facets and sort run on the result. */
	const visibleAgents = $derived.by(() => {
		const q = search.trim().toLowerCase();
		const searched = q
			? agents.filter((agent) =>
					[agent.name, agent.prompt, agent.ownerName ?? ""].some((text) =>
						text.toLowerCase().includes(q),
					),
				)
			: agents;
		return applySort(applyFilters(searched, filters, fieldMap), sortEntries, fieldMap);
	});

	function formatLastPost(value: string | null) {
		if (!value) return "Never posted";
		const date = new Date(value);
		if (Number.isNaN(date.getTime())) return "Never posted";

		const today = new Date();
		const startOfToday = new Date(
			today.getFullYear(),
			today.getMonth(),
			today.getDate(),
		);
		const startOfDay = new Date(
			date.getFullYear(),
			date.getMonth(),
			date.getDate(),
		);
		const dayDiff = Math.round(
			(startOfToday.getTime() - startOfDay.getTime()) / 86_400_000,
		);

		if (dayDiff === 0) return "Posted today";
		if (dayDiff === 1) return "Posted yesterday";
		return `Posted ${date.toLocaleDateString(undefined, {
			month: "short",
			day: "numeric",
			year:
				date.getFullYear() !== today.getFullYear()
					? "numeric"
					: undefined,
		})}`;
	}

	function scheduleLabel(agent: AgentListItem) {
		if (agent.schedules.length === 0) return "No schedule";
		if (agent.schedules.length === 1) return formatCron(agent.schedules[0]);
		return `${agent.schedules.length} schedules`;
	}

	const groups = $derived.by((): AgentGroup[] => {
		const active: AgentListItem[] = [];
		const inactive: AgentListItem[] = [];
		for (const agent of visibleAgents) {
			if (agent.isActive) active.push(agent);
			else inactive.push(agent);
		}
		const result: AgentGroup[] = [];
		if (active.length) {
			result.push({
				key: "active",
				title: "Active",
				hint: "Currently running",
				agents: active,
			});
		}
		if (inactive.length) {
			result.push({
				key: "inactive",
				title: "Inactive",
				hint: "Paused — won’t run",
				agents: inactive,
			});
		}
		return result;
	});

	function parseAgent(item: unknown): AgentListItem | null {
		if (
			!isRecord(item) ||
			typeof item.id !== "string" ||
			typeof item.name !== "string"
		) {
			return null;
		}
		return {
			id: item.id,
			name: item.name,
			prompt: typeof item.prompt === "string" ? item.prompt : "",
			isActive: item.isActive === true,
			profileImageUrl:
				typeof item.profileImageUrl === "string"
					? item.profileImageUrl
					: null,
			ownerName:
				typeof item.ownerName === "string" ? item.ownerName : null,
			llmModel: typeof item.llmModel === "string" ? item.llmModel : null,
			schedules: Array.isArray(item.schedules)
				? item.schedules.filter(
						(cron): cron is string => typeof cron === "string",
					)
				: [],
			lastPostAt:
				typeof item.lastPostAt === "string" ? item.lastPostAt : null,
		};
	}

	async function loadAgents() {
		loading = true;
		error = false;

		try {
			const response = await fetch("/api/agents");
			const payload: unknown = await response.json();

			if (
				!response.ok ||
				!isRecord(payload) ||
				!Array.isArray(payload.agents)
			) {
				throw new Error("Unable to load agents.");
			}

			agents = payload.agents
				.map(parseAgent)
				.filter((item): item is AgentListItem => item !== null);
		} catch {
			error = true;
		} finally {
			loading = false;
		}
	}

	onMount(() => {
		void loadAgents();
	});
</script>

<svelte:head>
	<title>Agents</title>
	<meta name="description" content="Browse the agents in your workspace." />
</svelte:head>

<Page title="Agents" lead="Browse the agents in your workspace." wide>
	<FilterToolbar
		{fields}
		items={agents}
		placeholder="Search agents…"
		bind:search
		bind:filters
		bind:sortEntries
	/>

	<section class="list-section" aria-label="Agent list">
		{#if loading}
			<div class="state-block" aria-busy="true">
				<UnicodeSpinner label="Loading agents" />
				<p class="state-text">Loading agents…</p>
			</div>
		{:else if error}
			<div class="state-block">
				<p class="state-text">Unable to load agents.</p>
				<button type="button" class="retry-btn" onclick={loadAgents}
					>Retry</button
				>
			</div>
		{:else if visibleAgents.length === 0}
			<div class="state-block">
				<p class="state-title">
					{narrowed ? "No matching agents" : "No agents yet"}
				</p>
				<p class="state-text">
					{narrowed
						? "Try clearing a filter or searching for something else."
						: "Agents you create will show up here."}
				</p>
				{#if narrowed}
					<button
						type="button"
						class="retry-btn"
						onclick={() => {
							filters = [];
							search = "";
						}}>Clear filters</button
					>
				{/if}
			</div>
		{:else}
			<div class="board">
				{#each groups as group (group.key)}
					<section
						class="board-group"
						class:tone-inactive={group.key === "inactive"}
						aria-label={group.title}
					>
						<header class="board-group-head">
							<div class="board-group-title-row">
								<h2 class="board-group-title">{group.title}</h2>
								<span class="board-group-count"
									>{group.agents.length}</span
								>
							</div>
							<p class="board-group-hint">{group.hint}</p>
						</header>

						<ul class="board-list">
							{#each group.agents as agent (agent.id)}
								<li>
									<a
										class="agent-row"
										href={resolve("/(chat)/agents/[id]", {
											id: agent.id,
										})}
									>
									<span class="agent-avatar" aria-hidden="true">
										{#if agent.profileImageUrl}
											<img
												class="agent-pfp"
												src={agent.profileImageUrl}
												alt=""
												loading="lazy"
											/>
										{:else}
											<AgentIdenticon
												name={agent.name}
												agentId={agent.id}
												isActive={agent.isActive}
												size={30}
											/>
										{/if}
									</span>

									<span class="agent-copy">
										<span class="agent-name-row">
											<span class="agent-name"
												title={agent.name}
												>{agent.name}</span
											>
											{#if agent.llmModel}
												<span class="agent-model"
													>{agent.llmModel}</span
												>
											{/if}
										</span>
										<span class="agent-meta">
											<span
												class="agent-schedule"
												title={agent.schedules[0] ??
													undefined}
											>
												{scheduleLabel(agent)}
											</span>
											{#if agent.ownerName}
												<span
													class="agent-owner"
													title={agent.ownerName}
													>{agent.ownerName}</span
												>
											{/if}
										</span>
									</span>

									<span class="agent-side">
										{formatLastPost(agent.lastPostAt)}
									</span>
									</a>
								</li>
							{/each}
						</ul>
					</section>
				{/each}
			</div>
		{/if}
	</section>
</Page>

<style>
	.retry-btn {
		border: 0;
		background: transparent;
		font: inherit;
		cursor: pointer;
	}

	.list-section {
		display: flex;
		flex-direction: column;
		gap: 14px;
		width: 100%;
		flex: 1;
		min-height: 0;
		overflow-y: auto;
	}

	.board {
		display: flex;
		flex-direction: column;
		gap: 28px;
		width: 100%;
	}

	.board-group {
		display: flex;
		flex-direction: column;
		gap: 10px;
		min-width: 0;
	}

	.board-group-head {
		display: flex;
		flex-direction: column;
		gap: 2px;
		padding-inline: 2px;
	}

	.board-group-title-row {
		display: flex;
		align-items: baseline;
		gap: 8px;
	}

	.board-group-title {
		margin: 0;
		color: var(--color-ink);
		font-family: var(--font-sans);
		font-size: 12px;
		font-weight: 600;
		letter-spacing: 0.06em;
		text-transform: uppercase;
	}

	.board-group-count {
		color: var(--color-muted);
		font-family: var(--font-mono, ui-monospace, monospace);
		font-size: 11px;
		font-weight: 500;
	}

	.board-group-hint {
		margin: 0;
		color: var(--color-muted);
		font-size: 11.5px;
		line-height: 1.4;
	}

	.board-list {
		display: flex;
		flex-direction: column;
		gap: 2px;
		margin: 0;
		padding: 0;
		list-style: none;
	}

	.agent-row {
		display: grid;
		grid-template-columns: auto minmax(0, 1fr) auto;
		align-items: center;
		column-gap: 12px;
		min-width: 0;
		padding: 10px 10px;
		border-radius: var(--radius-sm);
		color: inherit;
		text-decoration: none;
		cursor: pointer;
		transition: background 120ms ease;
	}

	.agent-row:hover {
		background: color-mix(in srgb, var(--color-elevate) 70%, transparent);
	}

	.agent-avatar {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		flex-shrink: 0;
		width: 30px;
		height: 30px;
		border-radius: var(--radius-sm);
		overflow: hidden;
		color: var(--color-ink);
		background: color-mix(in srgb, var(--color-line) 30%, transparent);
	}

	.agent-pfp {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}

	.agent-copy {
		display: flex;
		flex-direction: column;
		gap: 2px;
		min-width: 0;
	}

	.agent-name-row {
		display: flex;
		align-items: center;
		gap: 8px;
		min-width: 0;
	}

	.agent-name {
		min-width: 0;
		overflow: hidden;
		color: var(--color-ink);
		font-family: var(--font-sans);
		font-size: 13px;
		font-weight: 500;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.board-group.tone-inactive .agent-name {
		color: color-mix(in srgb, var(--color-ink) 72%, var(--color-muted));
	}

	.agent-model {
		flex-shrink: 0;
		padding: 1px 6px;
		border-radius: 999px;
		color: var(--color-muted);
		background: color-mix(in srgb, var(--color-line) 30%, transparent);
		font-size: 10px;
		font-weight: 500;
		letter-spacing: 0.02em;
	}

	.agent-meta {
		display: flex;
		align-items: center;
		gap: 10px;
		min-width: 0;
	}

	.agent-schedule,
	.agent-owner {
		min-width: 0;
		overflow: hidden;
		color: var(--color-muted);
		font-family: var(--font-sans);
		font-size: 11.5px;
		line-height: 1.35;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.agent-side {
		flex-shrink: 0;
		color: var(--color-muted);
		font-size: 11.5px;
		white-space: nowrap;
	}

	.state-block {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 10px;
		padding: 48px 16px;
		text-align: center;
	}

	.state-title {
		margin: 0;
		color: var(--color-ink);
		font-size: 15px;
		font-weight: 500;
	}

	.state-text {
		margin: 0;
		color: var(--color-muted);
		font-size: 13px;
		line-height: 1.45;
	}

	.retry-btn {
		padding: 6px 10px;
		border-radius: var(--radius-sm);
		color: var(--color-accent);
		font-size: 12.5px;
	}

	.retry-btn:hover {
		background: color-mix(in srgb, var(--color-elevate) 60%, transparent);
	}

	@media (max-width: 560px) {
		.agent-row {
			grid-template-columns: auto minmax(0, 1fr);
			row-gap: 6px;
		}

		.agent-side {
			grid-column: 2;
		}
	}
</style>

// examples/react-demo/src/components/AgentsPage.tsx
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';

import { formatCron } from '../lib/cron';
import { cx } from '../lib/cx';
import { applyFilters, type ColumnFilter, type FilterableColumn } from '../lib/tableFilter';
import { applySort, type SortableColumn, type SortEntry } from '../lib/tableSort';
import { usePageDescription, usePageTitle } from '../lib/usePageTitle';
import { isRecord } from '../lib/utils';
import { Page } from '../primitives';
import { FilterToolbar } from './filterToolbar';
import type { FilterField } from './filterToolbar';
import { AgentIdenticon } from './AgentIdenticon';
import {
	BOARD,
	BOARD_GROUP,
	BOARD_GROUP_COUNT,
	BOARD_GROUP_HEAD,
	BOARD_GROUP_HINT,
	BOARD_GROUP_TITLE,
	BOARD_GROUP_TITLE_ROW,
	BOARD_LIST,
	LIST_SECTION_SCROLL,
	RETRY_BTN,
	STATE_BLOCK,
	STATE_TEXT,
	STATE_TITLE
} from './pageStyles';
import { UnicodeSpinner } from './UnicodeSpinner';

type AgentListItem = {
	id: string;
	name: string;
	prompt: string;
	isActive: boolean;
	profileImageUrl: string | null;
	ownerName: string | null;
	llmModel: string | null;
	schedules: string[];
	lastPostAt: string | null;
};

type AgentGroup = {
	key: 'active' | 'inactive';
	title: string;
	hint: string;
	agents: AgentListItem[];
};

const META = 'min-w-0 overflow-hidden font-sans text-[11.5px] leading-[1.35] text-ellipsis whitespace-nowrap text-muted';

function formatLastPost(value: string | null) {
	if (!value) return 'Never posted';
	const date = new Date(value);
	if (Number.isNaN(date.getTime())) return 'Never posted';

	const today = new Date();
	const startOfToday = new Date(today.getFullYear(), today.getMonth(), today.getDate());
	const startOfDay = new Date(date.getFullYear(), date.getMonth(), date.getDate());
	const dayDiff = Math.round((startOfToday.getTime() - startOfDay.getTime()) / 86_400_000);

	if (dayDiff === 0) return 'Posted today';
	if (dayDiff === 1) return 'Posted yesterday';
	return `Posted ${date.toLocaleDateString(undefined, {
		month: 'short',
		day: 'numeric',
		year: date.getFullYear() !== today.getFullYear() ? 'numeric' : undefined
	})}`;
}

function scheduleLabel(agent: AgentListItem) {
	if (agent.schedules.length === 0) return 'No schedule';
	if (agent.schedules.length === 1) return formatCron(agent.schedules[0]);
	return `${agent.schedules.length} schedules`;
}

function parseAgent(item: unknown): AgentListItem | null {
	if (!isRecord(item) || typeof item.id !== 'string' || typeof item.name !== 'string') {
		return null;
	}
	return {
		id: item.id,
		name: item.name,
		prompt: typeof item.prompt === 'string' ? item.prompt : '',
		isActive: item.isActive === true,
		profileImageUrl: typeof item.profileImageUrl === 'string' ? item.profileImageUrl : null,
		ownerName: typeof item.ownerName === 'string' ? item.ownerName : null,
		llmModel: typeof item.llmModel === 'string' ? item.llmModel : null,
		schedules: Array.isArray(item.schedules)
			? item.schedules.filter((cron): cron is string => typeof cron === 'string')
			: [],
		lastPostAt: typeof item.lastPostAt === 'string' ? item.lastPostAt : null
	};
}

export function AgentsPage() {
	usePageTitle('Agents');
	usePageDescription('Browse the agents in your workspace.');

	const [agents, setAgents] = useState<AgentListItem[]>([]);
	const [search, setSearch] = useState('');
	const [filters, setFilters] = useState<ColumnFilter[]>([]);
	const [sortEntries, setSortEntries] = useState<SortEntry[]>([
		{ columnId: 'lastPost', dir: 'desc' }
	]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState(false);

	async function loadAgents() {
		setLoading(true);
		setError(false);

		try {
			const response = await fetch('/api/agents');
			const payload: unknown = await response.json();

			if (!response.ok || !isRecord(payload) || !Array.isArray(payload.agents)) {
				throw new Error('Unable to load agents.');
			}

			setAgents(
				payload.agents.map(parseAgent).filter((item): item is AgentListItem => item !== null)
			);
		} catch {
			setError(true);
		} finally {
			setLoading(false);
		}
	}

	useEffect(() => {
		void loadAgents();
	}, []);

	// ListAgents takes no search/sort/paging params, so this surface filters
	// client-side: facet options come from the loaded rows via `items`.
	const fields = useMemo<FilterField<AgentListItem>[]>(
		() => [
			{
				id: 'lastPost',
				header: 'Last post',
				sortable: true,
				sortType: 'date',
				sortValue: (agent) => (agent.lastPostAt ? new Date(agent.lastPostAt) : null)
			},
			{ id: 'name', header: 'Name', sortable: true, sortType: 'text' },
			{
				id: 'status',
				header: 'Status',
				filterable: true,
				filterValue: (agent) => (agent.isActive ? 'Active' : 'Inactive')
			},
			{
				id: 'ownerName',
				header: 'Owner',
				filterable: true,
				filterKind: 'people',
				filterValue: (agent) => agent.ownerName ?? ''
			},
			{
				id: 'llmModel',
				header: 'Model',
				filterable: true,
				filterValue: (agent) => agent.llmModel ?? ''
			},
			{
				id: 'schedule',
				header: 'Schedule',
				filterable: true,
				filterValue: (agent) => (agent.schedules.length ? 'Scheduled' : 'No schedule')
			}
		],
		[]
	);

	const fieldMap = useMemo(
		() =>
			new Map(fields.map((field) => [field.id, field])) as Map<
				string,
				FilterableColumn<AgentListItem> & SortableColumn<AgentListItem>
			>,
		[fields]
	);

	const narrowed = filters.length > 0 || search.trim().length > 0;

	/** Search matches name, prompt and owner; facets and sort run on the result. */
	const visibleAgents = useMemo(() => {
		const q = search.trim().toLowerCase();
		const searched = q
			? agents.filter((agent) =>
					[agent.name, agent.prompt, agent.ownerName ?? ''].some((text) =>
						text.toLowerCase().includes(q)
					)
				)
			: agents;
		return applySort(applyFilters(searched, filters, fieldMap), sortEntries, fieldMap);
	}, [agents, search, filters, sortEntries, fieldMap]);

	const active = visibleAgents.filter((agent) => agent.isActive);
	const inactive = visibleAgents.filter((agent) => !agent.isActive);
	const groups: AgentGroup[] = [];
	if (active.length) {
		groups.push({ key: 'active', title: 'Active', hint: 'Currently running', agents: active });
	}
	if (inactive.length) {
		groups.push({
			key: 'inactive',
			title: 'Inactive',
			hint: 'Paused — won’t run',
			agents: inactive
		});
	}

	return (
		<Page title="Agents" lead="Browse the agents in your workspace." wide>
			<FilterToolbar
				fields={fields}
				items={agents}
				placeholder="Search agents…"
				search={search}
				onSearchChange={setSearch}
				filters={filters}
				onFiltersChange={setFilters}
				sortEntries={sortEntries}
				onSortChange={setSortEntries}
			/>

			<section className={LIST_SECTION_SCROLL} aria-label="Agent list">
				{loading ? (
					<div className={STATE_BLOCK} aria-busy="true">
						<UnicodeSpinner label="Loading agents" />
						<p className={STATE_TEXT}>Loading agents…</p>
					</div>
				) : error ? (
					<div className={STATE_BLOCK}>
						<p className={STATE_TEXT}>Unable to load agents.</p>
						<button type="button" className={RETRY_BTN} onClick={loadAgents}>
							Retry
						</button>
					</div>
				) : visibleAgents.length === 0 ? (
					<div className={STATE_BLOCK}>
						<p className={STATE_TITLE}>{narrowed ? 'No matching agents' : 'No agents yet'}</p>
						<p className={STATE_TEXT}>
							{narrowed
								? 'Try clearing a filter or searching for something else.'
								: 'Agents you create will show up here.'}
						</p>
						{narrowed && (
							<button
								type="button"
								className={RETRY_BTN}
								onClick={() => {
									setFilters([]);
									setSearch('');
								}}
							>
								Clear filters
							</button>
						)}
					</div>
				) : (
					<div className={BOARD}>
						{groups.map((group) => (
							<section key={group.key} className={BOARD_GROUP} aria-label={group.title}>
								<header className={BOARD_GROUP_HEAD}>
									<div className={BOARD_GROUP_TITLE_ROW}>
										<h2 className={BOARD_GROUP_TITLE}>{group.title}</h2>
										<span className={BOARD_GROUP_COUNT}>{group.agents.length}</span>
									</div>
									<p className={BOARD_GROUP_HINT}>{group.hint}</p>
								</header>

								<ul className={BOARD_LIST}>
									{group.agents.map((agent) => (
										<li key={agent.id}>
											<Link
												className="grid min-w-0 cursor-pointer grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-x-3 rounded-sm p-2.5 text-inherit no-underline transition-[background] duration-[120ms] hover:bg-elevate/70 max-[560px]:grid-cols-[auto_minmax(0,1fr)] max-[560px]:gap-y-1.5"
												to={`/agents/${agent.id}`}
											>
												<span className="inline-flex size-[30px] shrink-0 items-center justify-center overflow-hidden rounded-sm bg-line/30 text-ink">
													{agent.profileImageUrl ? (
														<img
															className="size-full object-cover"
															src={agent.profileImageUrl}
															alt=""
															loading="lazy"
														/>
													) : (
														<AgentIdenticon
															name={agent.name}
															agentId={agent.id}
															isActive={agent.isActive}
															size={30}
														/>
													)}
												</span>

												<span className="flex min-w-0 flex-col gap-0.5">
													<span className="flex min-w-0 items-center gap-2">
														<span
															className={cx(
																'min-w-0 overflow-hidden font-sans text-[13px] font-medium text-ellipsis whitespace-nowrap',
																group.key === 'inactive'
																	? 'text-[color-mix(in_srgb,var(--color-ink)_72%,var(--color-muted))]'
																	: 'text-ink'
															)}
															title={agent.name}
														>
															{agent.name}
														</span>
														{agent.llmModel && (
															<span className="shrink-0 rounded-full bg-line/30 px-1.5 py-px text-[10px] font-medium tracking-[0.02em] text-muted">
																{agent.llmModel}
															</span>
														)}
													</span>
													<span className="flex min-w-0 items-center gap-2.5">
														<span className={META} title={agent.schedules[0] ?? undefined}>
															{scheduleLabel(agent)}
														</span>
														{agent.ownerName && (
															<span className={META} title={agent.ownerName}>
																{agent.ownerName}
															</span>
														)}
													</span>
												</span>

												<span className="shrink-0 text-[11.5px] whitespace-nowrap text-muted max-[560px]:col-start-2">
													{formatLastPost(agent.lastPostAt)}
												</span>
											</Link>
										</li>
									))}
								</ul>
							</section>
						))}
					</div>
				)}
			</section>
		</Page>
	);
}
