// examples/svelte-demo/src/lib/components/AppsPage.svelte
<script lang="ts">
	import Database from "@lucide/svelte/icons/database";
	import Star from "@lucide/svelte/icons/star";
	import CalendarClock from "@lucide/svelte/icons/calendar-clock";
	import { onMount } from "svelte";
	import { resolve } from "$app/paths";
	import UnicodeSpinner from "$lib/components/UnicodeSpinner.svelte";
	import { Page } from "$lib/primitives";
	import { isRecord } from "$lib/utils";

	type AppListItem = {
		id: string;
		name: string;
		description: string | null;
		screenshotUrl: string | null;
		isFavorited: boolean;
		hasUnpublishedChanges: boolean;
		scheduleEnabled: boolean;
		dataSourceCount: number;
		updatedAt: string | null;
	};

	let apps = $state<AppListItem[]>([]);
	let loading = $state(true);
	let error = $state(false);

	function monogram(name: string): string {
		return name?.trim().charAt(0).toUpperCase() || "A";
	}

	function formatUpdated(value: string | null) {
		if (!value) return null;
		const date = new Date(value);
		if (Number.isNaN(date.getTime())) return null;
		const today = new Date();
		return `Updated ${date.toLocaleDateString(undefined, {
			month: "short",
			day: "numeric",
			year:
				date.getFullYear() !== today.getFullYear() ? "numeric" : undefined,
		})}`;
	}

	function parseApp(item: unknown): AppListItem | null {
		if (!isRecord(item) || typeof item.id !== "string") return null;
		return {
			id: item.id,
			name: typeof item.name === "string" ? item.name : "Untitled app",
			description:
				typeof item.description === "string" ? item.description : null,
			screenshotUrl:
				typeof item.screenshotUrl === "string" ? item.screenshotUrl : null,
			isFavorited: item.isFavorited === true,
			hasUnpublishedChanges: item.hasUnpublishedChanges === true,
			scheduleEnabled: item.scheduleEnabled === true,
			dataSourceCount:
				typeof item.dataSourceCount === "number" ? item.dataSourceCount : 0,
			updatedAt: typeof item.updatedAt === "string" ? item.updatedAt : null,
		};
	}

	async function loadApps() {
		loading = true;
		error = false;

		try {
			const response = await fetch("/api/apps");
			const payload: unknown = await response.json();

			if (!response.ok || !isRecord(payload) || !Array.isArray(payload.apps)) {
				throw new Error("Unable to load apps.");
			}

			apps = payload.apps
				.map(parseApp)
				.filter((item): item is AppListItem => item !== null);
		} catch {
			error = true;
		} finally {
			loading = false;
		}
	}

	onMount(() => {
		void loadApps();
	});
</script>

<svelte:head>
	<title>Data apps</title>
	<meta name="description" content="Browse the data apps in your workspace." />
</svelte:head>

<Page title="Data apps" lead="Browse the data apps in your workspace." wide>
	<section class="list-section" aria-label="Data app list">
		{#if loading}
			<div class="state-block" aria-busy="true">
				<UnicodeSpinner label="Loading apps" />
				<p class="state-text">Loading apps…</p>
			</div>
		{:else if error}
			<div class="state-block">
				<p class="state-text">Unable to load apps.</p>
				<button type="button" class="retry-btn" onclick={loadApps}>Retry</button>
			</div>
		{:else if apps.length === 0}
			<div class="state-block">
				<p class="state-title">No data apps yet</p>
				<p class="state-text">Data apps you create will show up here.</p>
			</div>
		{:else}
			<ul class="app-grid">
				{#each apps as app (app.id)}
					{@const updated = formatUpdated(app.updatedAt)}
					<li>
						<a
							class="app-card"
							href={resolve("/(chat)/apps/[id]", { id: app.id })}
						>
							<span class="app-thumb fallback-tile" aria-hidden="true">
								{#if app.screenshotUrl}
									<!-- Screenshot framed as a mini window rising from the card body. -->
									<span class="app-window">
										<span class="app-window-bar">
											<span class="app-window-dot"></span>
											<span class="app-window-dot"></span>
											<span class="app-window-dot"></span>
										</span>
										<img
											class="app-shot"
											src={app.screenshotUrl}
											alt=""
											loading="lazy"
										/>
										<span class="app-fade"></span>
									</span>
								{:else}
									<span class="app-monogram">{monogram(app.name)}</span>
								{/if}
								{#if app.isFavorited}
									<Star
										class="app-fav"
										size={14}
										strokeWidth={2}
										fill="currentColor"
									/>
								{/if}
							</span>

							<span class="app-body">
								<span class="app-name" title={app.name}>{app.name}</span>
								{#if app.description}
									<span class="app-desc">{app.description}</span>
								{/if}

								<span class="app-meta">
									<span class="app-tag" title="Data sources">
										<Database size={12} strokeWidth={1.75} />
										{app.dataSourceCount}
									</span>
									{#if app.scheduleEnabled}
										<span class="app-tag" title="Scheduled">
											<CalendarClock size={12} strokeWidth={1.75} />
											Scheduled
										</span>
									{/if}
									{#if app.hasUnpublishedChanges}
										<span class="app-tag tone-warn" title="Unpublished changes"
											>Draft</span
										>
									{/if}
									{#if updated}
										<span class="app-updated">{updated}</span>
									{/if}
								</span>
							</span>
						</a>
					</li>
				{/each}
			</ul>
		{/if}
	</section>
</Page>

<style>
	.list-section {
		display: flex;
		flex-direction: column;
		gap: 14px;
		width: 100%;
		flex: 1;
		min-height: 0;
		overflow-y: auto;
	}

	.app-grid {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
		gap: 12px;
		margin: 0;
		padding: 0;
		list-style: none;
	}

	.app-card {
		display: flex;
		flex-direction: column;
		height: 100%;
		border: 1px solid color-mix(in srgb, var(--color-line) 60%, transparent);
		border-radius: var(--radius-md, 10px);
		overflow: hidden;
		color: inherit;
		text-decoration: none;
		background: color-mix(in srgb, var(--color-elevate) 40%, transparent);
		transition:
			background 120ms ease,
			border-color 120ms ease;
	}

	.app-card:hover {
		border-color: color-mix(in srgb, var(--color-accent) 45%, var(--color-line));
		background: color-mix(in srgb, var(--color-elevate) 70%, transparent);
	}

	.app-thumb {
		position: relative;
		display: flex;
		align-items: center;
		justify-content: center;
		height: 128px;
		flex-shrink: 0;
		overflow: hidden;
	}

	/* Dot-grid tile behind card previews so any app palette sits well on the surface. */
	.fallback-tile {
		background-color: var(--color-bg, #fff);
		background-image: radial-gradient(
			circle,
			color-mix(in srgb, var(--color-accent) 12%, transparent) 1px,
			transparent 1.5px
		);
		background-size: 14px 14px;
	}

	.app-window {
		position: absolute;
		inset: 20px 24px 0;
		display: flex;
		flex-direction: column;
		overflow: hidden;
		border: 1px solid color-mix(in srgb, var(--color-line) 60%, transparent);
		border-bottom: 0;
		border-radius: 8px 8px 0 0;
		background: var(--color-bg, #fff);
		box-shadow: 0 10px 30px -12px rgba(0, 0, 0, 0.25);
	}

	.app-window-bar {
		display: flex;
		align-items: center;
		gap: 5px;
		flex-shrink: 0;
		height: 18px;
		padding-inline: 8px;
		border-bottom: 1px solid color-mix(in srgb, var(--color-line) 40%, transparent);
		background: var(--color-bg, #fff);
	}

	.app-window-dot {
		width: 5px;
		height: 5px;
		border-radius: 999px;
		background: color-mix(in srgb, var(--color-line) 70%, transparent);
	}

	.app-shot {
		min-height: 0;
		width: 100%;
		flex: 1;
		object-fit: cover;
		object-position: top;
	}

	/* Fade the preview into the card body so the cut-off isn't abrupt. */
	.app-fade {
		position: absolute;
		inset-inline: 0;
		bottom: 0;
		height: 48px;
		background: linear-gradient(to bottom, transparent, var(--color-bg, #fff));
		pointer-events: none;
	}

	.app-monogram {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 52px;
		height: 52px;
		border: 1px solid color-mix(in srgb, var(--color-line) 60%, transparent);
		border-radius: 12px;
		background: var(--color-bg, #fff);
		box-shadow: var(--shadow-sm, 0 1px 2px rgba(0, 0, 0, 0.06));
		color: var(--color-accent);
		font-family: var(--font-sans);
		font-size: 22px;
		font-weight: 650;
	}

	:global(.app-thumb .app-fav) {
		position: absolute;
		top: 8px;
		right: 8px;
		color: var(--color-accent);
	}

	.app-body {
		display: flex;
		flex-direction: column;
		gap: 5px;
		padding: 12px;
		min-width: 0;
	}

	.app-name {
		overflow: hidden;
		color: var(--color-ink);
		font-family: var(--font-sans);
		font-size: 13.5px;
		font-weight: 600;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.app-desc {
		display: -webkit-box;
		-webkit-line-clamp: 2;
		line-clamp: 2;
		-webkit-box-orient: vertical;
		overflow: hidden;
		color: var(--color-muted);
		font-size: 12px;
		line-height: 1.45;
	}

	.app-meta {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		gap: 8px;
		margin-top: 3px;
	}

	.app-tag {
		display: inline-flex;
		align-items: center;
		gap: 4px;
		padding: 1px 7px;
		border-radius: 999px;
		color: var(--color-muted);
		background: color-mix(in srgb, var(--color-line) 30%, transparent);
		font-size: 10.5px;
		font-weight: 500;
	}

	.app-tag.tone-warn {
		color: var(--color-warn, #b58900);
		background: color-mix(in srgb, var(--color-warn, #b58900) 16%, transparent);
	}

	.app-updated {
		color: var(--color-muted);
		font-size: 10.5px;
		white-space: nowrap;
	}

	.state-block {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 10px;
		padding: 48px 16px;
		text-align: center;
	}

	.state-title {
		margin: 0;
		color: var(--color-ink);
		font-size: 15px;
		font-weight: 500;
	}

	.state-text {
		margin: 0;
		color: var(--color-muted);
		font-size: 13px;
		line-height: 1.45;
	}

	.retry-btn {
		border: 0;
		padding: 6px 10px;
		border-radius: var(--radius-sm);
		background: transparent;
		color: var(--color-accent);
		font: inherit;
		font-size: 12.5px;
		cursor: pointer;
	}

	.retry-btn:hover {
		background: color-mix(in srgb, var(--color-elevate) 60%, transparent);
	}
</style>

// examples/react-demo/src/components/AppsPage.tsx
import { CalendarClock, Database, Star } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

import { cx } from '../lib/cx';
import { usePageDescription, usePageTitle } from '../lib/usePageTitle';
import { isRecord } from '../lib/utils';
import { Page } from '../primitives';
import { LIST_SECTION_SCROLL, RETRY_BTN, STATE_BLOCK, STATE_TEXT, STATE_TITLE } from './pageStyles';
import { UnicodeSpinner } from './UnicodeSpinner';

type AppListItem = {
	id: string;
	name: string;
	description: string | null;
	screenshotUrl: string | null;
	isFavorited: boolean;
	hasUnpublishedChanges: boolean;
	scheduleEnabled: boolean;
	dataSourceCount: number;
	updatedAt: string | null;
};

const TAG =
	'inline-flex items-center gap-1 rounded-full bg-line/30 px-[7px] py-px text-[10.5px] font-medium text-muted';

function monogram(name: string): string {
	return name?.trim().charAt(0).toUpperCase() || 'A';
}

function formatUpdated(value: string | null) {
	if (!value) return null;
	const date = new Date(value);
	if (Number.isNaN(date.getTime())) return null;
	const today = new Date();
	return `Updated ${date.toLocaleDateString(undefined, {
		month: 'short',
		day: 'numeric',
		year: date.getFullYear() !== today.getFullYear() ? 'numeric' : undefined
	})}`;
}

function parseApp(item: unknown): AppListItem | null {
	if (!isRecord(item) || typeof item.id !== 'string') return null;
	return {
		id: item.id,
		name: typeof item.name === 'string' ? item.name : 'Untitled app',
		description: typeof item.description === 'string' ? item.description : null,
		screenshotUrl: typeof item.screenshotUrl === 'string' ? item.screenshotUrl : null,
		isFavorited: item.isFavorited === true,
		hasUnpublishedChanges: item.hasUnpublishedChanges === true,
		scheduleEnabled: item.scheduleEnabled === true,
		dataSourceCount: typeof item.dataSourceCount === 'number' ? item.dataSourceCount : 0,
		updatedAt: typeof item.updatedAt === 'string' ? item.updatedAt : null
	};
}

export function AppsPage() {
	usePageTitle('Data apps');
	usePageDescription('Browse the data apps in your workspace.');

	const [apps, setApps] = useState<AppListItem[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState(false);

	async function loadApps() {
		setLoading(true);
		setError(false);

		try {
			const response = await fetch('/api/apps');
			const payload: unknown = await response.json();

			if (!response.ok || !isRecord(payload) || !Array.isArray(payload.apps)) {
				throw new Error('Unable to load apps.');
			}

			setApps(payload.apps.map(parseApp).filter((item): item is AppListItem => item !== null));
		} catch {
			setError(true);
		} finally {
			setLoading(false);
		}
	}

	useEffect(() => {
		void loadApps();
	}, []);

	return (
		<Page title="Data apps" lead="Browse the data apps in your workspace." wide>
			<section className={LIST_SECTION_SCROLL} aria-label="Data app list">
				{loading ? (
					<div className={STATE_BLOCK} aria-busy="true">
						<UnicodeSpinner label="Loading apps" />
						<p className={STATE_TEXT}>Loading apps…</p>
					</div>
				) : error ? (
					<div className={STATE_BLOCK}>
						<p className={STATE_TEXT}>Unable to load apps.</p>
						<button type="button" className={RETRY_BTN} onClick={loadApps}>
							Retry
						</button>
					</div>
				) : apps.length === 0 ? (
					<div className={STATE_BLOCK}>
						<p className={STATE_TITLE}>No data apps yet</p>
						<p className={STATE_TEXT}>Data apps you create will show up here.</p>
					</div>
				) : (
					<ul className="m-0 grid list-none grid-cols-[repeat(auto-fill,minmax(240px,1fr))] gap-3 p-0">
						{apps.map((app) => {
							const updated = formatUpdated(app.updatedAt);
							return (
								<li key={app.id}>
									<Link
										className="flex h-full flex-col overflow-hidden rounded-md border border-line/60 bg-elevate/40 text-inherit no-underline transition-[background,border-color] duration-[120ms] hover:border-[color-mix(in_srgb,var(--color-accent)_45%,var(--color-line))] hover:bg-elevate/70"
										to={`/apps/${app.id}`}
									>
										{/* Dot-grid tile behind card previews so any app palette sits well on the surface. */}
										<span
											className="relative flex h-32 shrink-0 items-center justify-center overflow-hidden bg-[var(--color-bg,#fff)] bg-[radial-gradient(circle,color-mix(in_srgb,var(--color-accent)_12%,transparent)_1px,transparent_1.5px)] bg-[length:14px_14px]"
											aria-hidden="true"
										>
											{app.screenshotUrl ? (
												// Screenshot framed as a mini window rising from the card body.
												// Corners are 8px — `rounded-t-lg` would be 16px (--radius-lg).
												<span className="absolute inset-x-6 top-5 bottom-0 flex flex-col overflow-hidden rounded-t-[8px] border border-b-0 border-line/60 bg-[var(--color-bg,#fff)] shadow-[0_10px_30px_-12px_rgba(0,0,0,0.25)]">
													<span className="flex h-[18px] shrink-0 items-center gap-[5px] border-b border-line/40 bg-[var(--color-bg,#fff)] px-2">
														<span className="size-[5px] rounded-full bg-line/70" />
														<span className="size-[5px] rounded-full bg-line/70" />
														<span className="size-[5px] rounded-full bg-line/70" />
													</span>
													<img
														className="min-h-0 w-full flex-1 object-cover object-top"
														src={app.screenshotUrl}
														alt=""
														loading="lazy"
													/>
													{/* Fade the preview into the card body so the cut-off isn't abrupt. */}
													<span className="pointer-events-none absolute inset-x-0 bottom-0 h-12 bg-gradient-to-b from-transparent to-[var(--color-bg,#fff)]" />
												</span>
											) : (
												<span className="inline-flex size-[52px] items-center justify-center rounded-[12px] border border-line/60 bg-[var(--color-bg,#fff)] font-sans text-[22px] font-[650] text-accent shadow-[var(--shadow-sm,0_1px_2px_rgba(0,0,0,0.06))]">
													{monogram(app.name)}
												</span>
											)}
											{app.isFavorited && (
												<Star
													className="absolute top-2 right-2 text-accent"
													size={14}
													strokeWidth={2}
													fill="currentColor"
												/>
											)}
										</span>

										<span className="flex min-w-0 flex-col gap-[5px] p-3">
											<span
												className="overflow-hidden font-sans text-[13.5px] font-semibold text-ellipsis whitespace-nowrap text-ink"
												title={app.name}
											>
												{app.name}
											</span>
											{app.description && (
												<span className="line-clamp-2 overflow-hidden text-[12px] leading-[1.45] text-muted">
													{app.description}
												</span>
											)}

											<span className="mt-[3px] flex flex-wrap items-center gap-2">
												<span className={TAG} title="Data sources">
													<Database size={12} strokeWidth={1.75} />
													{app.dataSourceCount}
												</span>
												{app.scheduleEnabled && (
													<span className={TAG} title="Scheduled">
														<CalendarClock size={12} strokeWidth={1.75} />
														Scheduled
													</span>
												)}
												{app.hasUnpublishedChanges && (
													<span
														className={cx(
															TAG,
															'bg-[color-mix(in_srgb,var(--color-warn,#b58900)_16%,transparent)] text-[var(--color-warn,#b58900)]'
														)}
														title="Unpublished changes"
													>
														Draft
													</span>
												)}
												{updated && (
													<span className="text-[10.5px] whitespace-nowrap text-muted">{updated}</span>
												)}
											</span>
										</span>
									</Link>
								</li>
							);
						})}
					</ul>
				)}
			</section>
		</Page>
	);
}
