// examples/chat-demo/src/lib/components/RunningDuration.svelte
<script lang="ts">
	import { formatElapsed } from "$lib/cells";

	let {
		startedAtMs = null,
	}: {
		/** API timestamp in ms, or null to start the clock on mount. */
		startedAtMs?: number | null;
	} = $props();

	const mountMs = Date.now();
	let now = $state(Date.now());

	$effect(() => {
		now = Date.now();
		const id = setInterval(() => {
			now = Date.now();
		}, 1000);
		return () => clearInterval(id);
	});

	const label = $derived(
		`Running ${formatElapsed(now - (startedAtMs ?? mountMs))}`,
	);
</script>

<span class="running-duration" aria-live="polite">{label}</span>

<style>
	.running-duration {
		flex-shrink: 0;
		color: #a1a1aa;
		font-size: 11.5px;
		font-weight: 500;
		font-variant-numeric: tabular-nums;
		letter-spacing: 0.01em;
		white-space: nowrap;
	}
</style>

// examples/react-demo/src/components/RunningDuration.tsx
import { useEffect, useRef, useState } from 'react';

import { formatElapsed } from '../lib/cells';

type Props = {
	/** API timestamp in ms, or null to start the clock on mount. */
	startedAtMs?: number | null;
};

export function RunningDuration({ startedAtMs = null }: Props) {
	const mountMsRef = useRef(Date.now());
	const [now, setNow] = useState(() => Date.now());

	useEffect(() => {
		setNow(Date.now());
		const id = setInterval(() => setNow(Date.now()), 1000);
		return () => clearInterval(id);
	}, []);

	const label = `Running ${formatElapsed(now - (startedAtMs ?? mountMsRef.current))}`;

	return (
		<span
			className="shrink-0 whitespace-nowrap text-[11.5px] font-medium tracking-[0.01em] tabular-nums text-[#a1a1aa]"
			aria-live="polite"
		>
			{label}
		</span>
	);
}
