// examples/chat-demo/src/lib/components/ThinkingCell.svelte
<script lang="ts">
	import ChevronRight from '@lucide/svelte/icons/chevron-right';
	import type { CellLike } from '$lib/cells';
	import { getCellPayload } from '$lib/cells';

	let {
		cell,
		active = false
	}: {
		cell: CellLike;
		/** True while this thinking segment is still streaming. */
		active?: boolean;
	} = $props();

	const payload = $derived(getCellPayload(cell));
	const redacted = $derived(payload.redacted === true);
	const content = $derived(
		typeof payload.content === 'string' ? payload.content.trim() : ''
	);
	const hasContent = $derived(redacted || content.length > 0);
	const isThinking = $derived(active && !cell.complete);

	let expanded = $state(false);
	let openedManually = $state(false);

	// Live thoughts stay open while streaming...
	$effect(() => {
		if (isThinking) expanded = true;
	});

	// ...then tuck away shortly after, unless the user opened them on purpose.
	$effect(() => {
		if (isThinking || !expanded || openedManually || !hasContent) return;
		const timeout = setTimeout(() => {
			expanded = false;
		}, 2000);
		return () => clearTimeout(timeout);
	});

	const visible = $derived(isThinking || hasContent);
	const showBody = $derived(expanded && hasContent);
	const bodyText = $derived(redacted ? 'Thinking (redacted)' : content);

	function toggle() {
		expanded = !expanded;
		openedManually = expanded;
	}
</script>

{#if visible}
	<div class="thinking">
		{#if isThinking}
			<div class="thinking-row">
				<span class="thinking-label shimmer">Thinking…</span>
			</div>
		{:else}
			<button type="button" class="thinking-toggle" onclick={toggle}>
				<ChevronRight size={14} class={['chevron', expanded && 'open']} />
				<span class="thinking-label">Thought process</span>
			</button>
		{/if}

		{#if showBody}
			<pre class="thinking-body">{bodyText}</pre>
		{/if}
	</div>
{/if}

<style>
	.thinking {
		width: 100%;
	}

	.thinking-row,
	.thinking-toggle {
		display: flex;
		align-items: center;
		gap: 6px;
		width: 100%;
		min-height: 32px;
		padding: 4px 6px;
		border: 0;
		border-radius: var(--radius-sm, 8px);
		background: transparent;
		font: inherit;
		text-align: left;
	}

	.thinking-toggle {
		cursor: pointer;
	}

	.thinking-toggle:hover {
		background: color-mix(in srgb, var(--color-ink) 4%, transparent);
	}

	.thinking-toggle :global(.chevron) {
		flex-shrink: 0;
		color: #a1a1aa;
		transition: transform 0.15s ease;
	}

	.thinking-toggle :global(.chevron.open) {
		transform: rotate(90deg);
	}

	.thinking-label {
		overflow: hidden;
		min-width: 0;
		color: var(--color-muted);
		font-size: 13px;
		font-weight: 500;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.shimmer {
		background: linear-gradient(90deg, #a1a1aa 25%, #3f3f46 50%, #a1a1aa 75%);
		background-size: 200% 100%;
		background-clip: text;
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		animation: shimmer 1.6s linear infinite;
	}

	@keyframes shimmer {
		0% {
			background-position: 200% 0;
		}
		100% {
			background-position: -200% 0;
		}
	}

	@media (prefers-reduced-motion: reduce) {
		.shimmer {
			background: none;
			-webkit-text-fill-color: currentColor;
			animation: none;
		}

		.thinking-toggle :global(.chevron) {
			transition: none;
		}
	}

	.thinking-body {
		margin: 0;
		padding: 2px 8px 8px 22px;
		border-left: 2px solid var(--color-line);
		margin-left: 12px;
		color: #a1a1aa;
		font-family: inherit;
		font-size: 12.5px;
		font-style: italic;
		line-height: 1.55;
		white-space: pre-wrap;
		overflow-wrap: anywhere;
	}
</style>

// examples/react-demo/src/components/ThinkingCell.tsx
import { ChevronRight } from 'lucide-react';
import { useEffect, useState } from 'react';

import { getCellPayload, type CellLike } from '../lib/cells';
import { cx } from '../lib/cx';

type Props = {
	cell: CellLike;
	/** True while this thinking segment is still streaming. */
	active?: boolean;
};

const ROW =
	'flex w-full min-h-8 items-center gap-1.5 rounded-sm border-0 bg-transparent px-1.5 py-1 text-left font-[inherit]';
const LABEL = 'min-w-0 overflow-hidden text-ellipsis whitespace-nowrap text-[13px] font-medium text-muted';

export function ThinkingCell({ cell, active = false }: Props) {
	const payload = getCellPayload(cell);
	const redacted = payload.redacted === true;
	const content = typeof payload.content === 'string' ? payload.content.trim() : '';
	const hasContent = redacted || content.length > 0;
	const isThinking = active && !cell.complete;

	const [expanded, setExpanded] = useState(false);
	const [openedManually, setOpenedManually] = useState(false);

	// Live thoughts stay open while streaming...
	useEffect(() => {
		if (isThinking) setExpanded(true);
	}, [isThinking]);

	// ...then tuck away shortly after, unless the user opened them on purpose.
	useEffect(() => {
		if (isThinking || !expanded || openedManually || !hasContent) return;
		const timeout = setTimeout(() => setExpanded(false), 2000);
		return () => clearTimeout(timeout);
	}, [isThinking, expanded, openedManually, hasContent]);

	const visible = isThinking || hasContent;
	const showBody = expanded && hasContent;
	const bodyText = redacted ? 'Thinking (redacted)' : content;

	if (!visible) return null;

	function toggle() {
		setExpanded((current) => {
			setOpenedManually(!current);
			return !current;
		});
	}

	return (
		<div className="w-full">
			{isThinking ? (
				<div className={ROW}>
					{/* .shimmer comes from app.css */}
					<span className={cx(LABEL, 'shimmer')}>Thinking…</span>
				</div>
			) : (
				<button type="button" className={cx(ROW, 'cursor-pointer hover:bg-ink/4')} onClick={toggle}>
					<ChevronRight
						size={14}
						className={cx(
							'shrink-0 text-[#a1a1aa] transition-transform duration-150 motion-reduce:transition-none',
							expanded && 'rotate-90'
						)}
					/>
					<span className={LABEL}>Thought process</span>
				</button>
			)}

			{showBody && (
				<pre className="m-0 ml-3 border-l-2 border-line py-0 pt-0.5 pr-2 pb-2 pl-[22px] font-[inherit] text-[12.5px] leading-[1.55] italic whitespace-pre-wrap text-[#a1a1aa] wrap-anywhere">
					{bodyText}
				</pre>
			)}
		</div>
	);
}
