// examples/svelte-demo/src/lib/components/TqlPreview.svelte
<script lang="ts">
	import Database from "@lucide/svelte/icons/database";
	import Layers from "@lucide/svelte/icons/layers";
	import SlidersHorizontal from "@lucide/svelte/icons/sliders-horizontal";
	import Filter from "@lucide/svelte/icons/filter";
	import ArrowDownLeft from "@lucide/svelte/icons/arrow-down-left";
	import FileText from "@lucide/svelte/icons/file-text";
	import Tag from "@lucide/svelte/icons/tag";
	import Link2 from "@lucide/svelte/icons/link-2";
	import PierreCode from "$lib/components/PierreCode.svelte";
	import {
		hasTqlStructure,
		parseTql,
		resolveImport,
		stripNounPrefix,
	} from "$lib/tqlParse";

	let {
		content,
		filePath = "",
		showSource = true,
		onNavigateToImport = undefined,
	}: {
		content: string;
		filePath?: string;
		showSource?: boolean;
		onNavigateToImport?: (resolvedPath: string) => void;
	} = $props();

	const parsed = $derived(parseTql(content));
	const hasStructure = $derived(hasTqlStructure(parsed));
</script>

<div class="tql">
	{#if hasStructure}
		<div class="sections">
			{#if parsed.role || parsed.title || parsed.description}
				<div class="head">
					{#if parsed.role || parsed.title}
						<div class="head-row">
							{#if parsed.title}
								<h4 class="title">{parsed.title}</h4>
							{/if}
							{#if parsed.role}
								<span
									class="role-badge"
									class:role-object={parsed.role === "Object module"}
									class:role-view={parsed.role === "Composed view"}
								>
									{parsed.role}
								</span>
							{/if}
						</div>
					{/if}
					{#if parsed.description}
						<p class="description">{parsed.description}</p>
					{/if}
				</div>
			{/if}

			{#if parsed.backing}
				<div class="backing">
					<div class="section-label">
						<Database size={12} />
						Backing Table
					</div>
					<p class="backing-value">{parsed.backing}</p>
				</div>
			{/if}

			{#if parsed.imports.length > 0}
				<div>
					<div class="section-label">
						<ArrowDownLeft size={12} />
						Imports
					</div>
					<div class="import-list">
						{#each parsed.imports as imp (imp.path)}
							<button
								type="button"
								class="import-row"
								disabled={!onNavigateToImport}
								onclick={() =>
									onNavigateToImport?.(resolveImport(filePath, imp.path))}
							>
								<span class="mono">{imp.alias}</span>
								<span class="import-path" title={imp.path}>{imp.path}</span>
							</button>
						{/each}
					</div>
				</div>
			{/if}

			{#if parsed.relations.length > 0}
				<div>
					<div class="section-label">
						<Link2 size={12} />
						Relations
						<span class="count">({parsed.relations.length})</span>
					</div>
					<div class="table-wrap">
						<table>
							<thead>
								<tr>
									<th>Joins</th>
									<th>On</th>
								</tr>
							</thead>
							<tbody>
								{#each parsed.relations as rel (rel.joined + "/" + rel.parent)}
									<tr>
										<td class="mono" title={`${rel.parent} → ${rel.joined}`}>
											{rel.joined}
										</td>
										<td class="mono muted">
											{rel.parent}.{rel.fk} = {rel.joined}.{rel.pk}
										</td>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
				</div>
			{/if}

			{#if parsed.params.length > 0}
				<div>
					<div class="section-label">
						<SlidersHorizontal size={12} />
						Parameters
					</div>
					<div class="table-wrap">
						<table>
							<thead>
								<tr>
									<th>Name</th>
									<th>Type</th>
									<th>Default</th>
								</tr>
							</thead>
							<tbody>
								{#each parsed.params as param (param.name)}
									<tr>
										<td class="mono">{param.name}</td>
										<td class="truncate" title={param.type}>{param.type}</td>
										<td class="mono muted">{param.default ?? "—"}</td>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
				</div>
			{/if}

			{#if parsed.metrics.length > 0}
				<div>
					<div class="section-label">
						<Layers size={12} />
						Metrics
						<span class="count">({parsed.metrics.length})</span>
					</div>
					{#if parsed.metrics.some((m) => m.expr)}
						<div class="table-wrap">
							<table>
								<thead>
									<tr>
										<th>Name</th>
										<th>Expression</th>
									</tr>
								</thead>
								<tbody>
									{#each parsed.metrics as metric (metric.name)}
										<tr>
											<td class="strong">{metric.name}</td>
											<td class="mono muted">{metric.expr ?? "—"}</td>
										</tr>
									{/each}
								</tbody>
							</table>
						</div>
					{:else}
						<div class="pills">
							{#each parsed.metrics as metric (metric.name)}
								<span class="pill">{metric.name}</span>
							{/each}
						</div>
					{/if}
				</div>
			{/if}

			{#if parsed.dimensions.length > 0}
				<div>
					<div class="section-label">
						<Tag size={12} />
						Dimensions
						<span class="count">({parsed.dimensions.length})</span>
					</div>
					{#if parsed.dimensions.some((d) => d.expr)}
						<div class="table-wrap">
							<table>
								<thead>
									<tr>
										<th>Label</th>
										<th>Column</th>
									</tr>
								</thead>
								<tbody>
									{#each parsed.dimensions as dim (dim.key)}
										<tr>
											<td class="strong">{dim.label}</td>
											<td class="mono muted">{dim.expr ?? "—"}</td>
										</tr>
									{/each}
								</tbody>
							</table>
						</div>
					{:else}
						<div class="pills">
							{#each parsed.dimensions as dim (dim.key)}
								<span class="pill">{dim.label}</span>
							{/each}
						</div>
					{/if}
				</div>
			{/if}

			{#if parsed.filters.length > 0}
				<div>
					<div class="section-label">
						<Filter size={12} />
						Filters
						<span class="count">({parsed.filters.length})</span>
					</div>
					<div class="pills">
						{#each parsed.filters as filter (filter)}
							<span class="pill">{stripNounPrefix(filter)}</span>
						{/each}
					</div>
				</div>
			{/if}

			{#if parsed.comments.length > 0}
				<div>
					<div class="section-label">
						<FileText size={12} />
						Details
					</div>
					<div class="details">
						{#each parsed.comments as comment, i (i)}
							<div class="detail-row">
								<span class="detail-key">{comment.key}</span>
								<span class="muted">{comment.value}</span>
							</div>
						{/each}
					</div>
				</div>
			{/if}
		</div>
	{/if}

	{#if showSource}
		<div class="source">
			<div class="source-head">Source</div>
			<PierreCode
				fileName={filePath || "file.tql"}
				contents={content}
				lang="sql"
				fill
			/>
		</div>
	{/if}
</div>

<style>
	.tql {
		display: flex;
		flex-direction: column;
		height: 100%;
		min-height: 0;
	}

	.sections {
		display: flex;
		flex-direction: column;
		gap: 16px;
	}

	.head-row {
		display: flex;
		align-items: center;
		gap: 8px;
	}

	.title {
		margin: 0;
		font-size: 13px;
		font-weight: 600;
		color: var(--color-ink);
	}

	.role-badge {
		display: inline-block;
		flex-shrink: 0;
		padding: 2px 8px;
		border-radius: 999px;
		font-size: 10px;
		font-weight: 600;
		letter-spacing: 0.04em;
		text-transform: uppercase;
		color: var(--color-text-3);
		background: color-mix(in srgb, var(--color-line) 35%, transparent);
	}

	.role-badge.role-object {
		color: #1d4ed8;
		background: color-mix(in srgb, var(--color-accent) 8%, var(--color-elevate));
	}

	.role-badge.role-view {
		color: #047857;
		background: #ecfdf5;
	}

	.description {
		margin: 2px 0 0;
		font-size: 12px;
		line-height: 1.5;
		color: var(--color-muted);
	}

	.section-label {
		display: flex;
		align-items: center;
		gap: 6px;
		padding-bottom: 6px;
		font-size: 10px;
		font-weight: 600;
		letter-spacing: 0.05em;
		text-transform: uppercase;
		color: var(--color-muted);
	}

	.count {
		color: color-mix(in srgb, var(--color-muted) 70%, transparent);
	}

	.backing {
		padding: 8px 12px;
		border-radius: var(--radius-sm, 8px);
		background: color-mix(in srgb, var(--color-ink) 4%, transparent);
	}

	.backing .section-label {
		padding-bottom: 4px;
	}

	.backing-value {
		margin: 0;
		font-family: var(--font-mono, ui-monospace, monospace);
		font-size: 12px;
		color: var(--color-ink);
	}

	.import-list {
		display: flex;
		flex-direction: column;
		gap: 4px;
	}

	.import-row {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 8px;
		width: 100%;
		padding: 6px 10px;
		border: 0;
		border-radius: 6px;
		text-align: left;
		background: color-mix(in srgb, var(--color-ink) 4%, transparent);
		font: inherit;
		transition: background 120ms ease;
	}

	.import-row:not(:disabled) {
		cursor: pointer;
	}

	.import-row:not(:disabled):hover {
		background: color-mix(in srgb, var(--color-ink) 8%, transparent);
	}

	.import-path {
		overflow: hidden;
		font-size: 11px;
		color: var(--color-muted);
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.table-wrap {
		overflow: hidden;
		border: 1px solid var(--color-line);
		border-radius: var(--radius-sm, 8px);
	}

	table {
		width: 100%;
		border-collapse: collapse;
		font-size: 12px;
	}

	th {
		padding: 6px 10px;
		text-align: left;
		font-weight: 500;
		color: var(--color-muted);
		background: color-mix(in srgb, var(--color-ink) 3%, transparent);
		border-bottom: 1px solid var(--color-line);
	}

	td {
		padding: 6px 10px;
		color: var(--color-ink);
		border-bottom: 1px solid
			color-mix(in srgb, var(--color-line) 60%, transparent);
	}

	tbody tr:last-child td {
		border-bottom: 0;
	}

	.mono {
		font-family: var(--font-mono, ui-monospace, monospace);
	}

	.muted {
		color: var(--color-muted);
	}

	.strong {
		font-weight: 500;
	}

	.truncate {
		max-width: 180px;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		color: var(--color-muted);
	}

	.pills {
		display: flex;
		flex-wrap: wrap;
		gap: 4px;
	}

	.pill {
		padding: 2px 8px;
		border-radius: 6px;
		font-size: 11px;
		font-weight: 500;
		color: var(--color-text-2);
		background: color-mix(in srgb, var(--color-ink) 6%, transparent);
	}

	.details {
		display: flex;
		flex-direction: column;
		gap: 4px;
	}

	.detail-row {
		display: flex;
		gap: 8px;
		font-size: 12px;
	}

	.detail-key {
		flex-shrink: 0;
		font-weight: 500;
		color: var(--color-text-3);
	}

	.source {
		display: flex;
		flex-direction: column;
		flex: 1;
		min-height: 0;
		margin-top: 16px;
		border: 1px solid var(--color-line);
		border-radius: var(--radius-sm, 8px);
		overflow: hidden;
	}

	.source-head {
		flex-shrink: 0;
		padding: 6px 12px;
		font-size: 10px;
		font-weight: 600;
		letter-spacing: 0.05em;
		text-transform: uppercase;
		color: var(--color-muted);
		background: color-mix(in srgb, var(--color-ink) 3%, transparent);
		border-bottom: 1px solid var(--color-line);
	}
</style>

// examples/react-demo/src/components/TqlPreview.tsx
import {
	ArrowDownLeft,
	Database,
	FileText,
	Filter,
	Layers,
	Link2,
	SlidersHorizontal,
	Tag
} from 'lucide-react';
import type { ReactNode } from 'react';

import { cx } from '../lib/cx';
import { hasTqlStructure, parseTql, resolveImport, stripNounPrefix } from '../lib/tqlParse';
import { PierreCode } from './PierreCode';

type Props = {
	content: string;
	filePath?: string;
	showSource?: boolean;
	onNavigateToImport?: (resolvedPath: string) => void;
};

// Padding is applied per use-site: stacking `pb-1` on top of a constant that
// already carries `pb-1.5` would let Tailwind's rule order pick the winner.
const LABEL_BASE =
	'flex items-center gap-1.5 text-[10px] font-semibold tracking-[0.05em] text-muted uppercase';
const LABEL = `${LABEL_BASE} pb-1.5`;
const COUNT = 'text-[color-mix(in_srgb,var(--color-muted)_70%,transparent)]';
const TABLE_WRAP = 'overflow-hidden rounded-xs border border-line';
const TABLE = 'w-full border-collapse text-[12px]';
const TH =
	'border-b border-line bg-ink/3 px-2.5 py-1.5 text-left font-medium text-muted';
const TD = 'border-b border-line/60 px-2.5 py-1.5 text-ink';
const MONO = 'font-mono';
const MUTED = 'text-muted';
const PILL = 'rounded-xs bg-ink/6 px-2 py-0.5 text-[11px] font-medium text-text-2';

function Section({ label, children }: { label: ReactNode; children: ReactNode }) {
	return (
		<div>
			<div className={LABEL}>{label}</div>
			{children}
		</div>
	);
}

export function TqlPreview({
	content,
	filePath = '',
	showSource = true,
	onNavigateToImport = undefined
}: Props) {
	const parsed = parseTql(content);
	const hasStructure = hasTqlStructure(parsed);

	return (
		<div className="flex h-full min-h-0 flex-col">
			{hasStructure && (
				<div className="flex flex-col gap-4">
					{(parsed.role || parsed.title || parsed.description) && (
						<div>
							{(parsed.role || parsed.title) && (
								<div className="flex items-center gap-2">
									{parsed.title && (
										<h4 className="m-0 text-[13px] font-semibold text-ink">{parsed.title}</h4>
									)}
									{parsed.role && (
										<span
											className={cx(
												'inline-block flex-shrink-0 rounded-full px-2 py-0.5 text-[10px] font-semibold tracking-[0.04em] uppercase',
												parsed.role === 'Object module'
													? 'bg-[color-mix(in_srgb,var(--color-accent)_8%,var(--color-elevate))] text-[#1d4ed8]'
													: parsed.role === 'Composed view'
														? 'bg-[#ecfdf5] text-[#047857]'
														: 'bg-line/35 text-text-3'
											)}
										>
											{parsed.role}
										</span>
									)}
								</div>
							)}
							{parsed.description && (
								<p className="mt-0.5 mb-0 text-[12px] leading-normal text-muted">
									{parsed.description}
								</p>
							)}
						</div>
					)}

					{parsed.backing && (
						<div className="rounded-xs bg-ink/4 px-3 py-2">
							<div className={`${LABEL_BASE} pb-1`}>
								<Database size={12} />
								Backing Table
							</div>
							<p className="m-0 font-mono text-[12px] text-ink">{parsed.backing}</p>
						</div>
					)}

					{parsed.imports.length > 0 && (
						<Section
							label={
								<>
									<ArrowDownLeft size={12} />
									Imports
								</>
							}
						>
							<div className="flex flex-col gap-1">
								{parsed.imports.map((imp) => (
									<button
										key={imp.path}
										type="button"
										className="flex w-full items-center justify-between gap-2 rounded-xs border-0 bg-ink/4 px-2.5 py-1.5 text-left transition-[background] duration-[120ms] not-disabled:cursor-pointer hover:not-disabled:bg-ink/8"
										disabled={!onNavigateToImport}
										onClick={() => onNavigateToImport?.(resolveImport(filePath, imp.path))}
									>
										<span className={MONO}>{imp.alias}</span>
										<span
											className="overflow-hidden text-[11px] text-ellipsis whitespace-nowrap text-muted"
											title={imp.path}
										>
											{imp.path}
										</span>
									</button>
								))}
							</div>
						</Section>
					)}

					{parsed.relations.length > 0 && (
						<Section
							label={
								<>
									<Link2 size={12} />
									Relations
									<span className={COUNT}>({parsed.relations.length})</span>
								</>
							}
						>
							<div className={TABLE_WRAP}>
								<table className={TABLE}>
									<thead>
										<tr>
											<th className={TH}>Joins</th>
											<th className={TH}>On</th>
										</tr>
									</thead>
									<tbody className="[&_tr:last-child_td]:border-b-0">
										{parsed.relations.map((rel) => (
											<tr key={`${rel.joined}/${rel.parent}`}>
												<td className={cx(TD, MONO)} title={`${rel.parent} → ${rel.joined}`}>
													{rel.joined}
												</td>
												<td className={cx(TD, MONO, MUTED)}>
													{rel.parent}.{rel.fk} = {rel.joined}.{rel.pk}
												</td>
											</tr>
										))}
									</tbody>
								</table>
							</div>
						</Section>
					)}

					{parsed.params.length > 0 && (
						<Section
							label={
								<>
									<SlidersHorizontal size={12} />
									Parameters
								</>
							}
						>
							<div className={TABLE_WRAP}>
								<table className={TABLE}>
									<thead>
										<tr>
											<th className={TH}>Name</th>
											<th className={TH}>Type</th>
											<th className={TH}>Default</th>
										</tr>
									</thead>
									<tbody className="[&_tr:last-child_td]:border-b-0">
										{parsed.params.map((param) => (
											<tr key={param.name}>
												<td className={cx(TD, MONO)}>{param.name}</td>
												<td
													className={cx(
														TD,
														'max-w-[180px] overflow-hidden text-ellipsis whitespace-nowrap text-muted'
													)}
													title={param.type}
												>
													{param.type}
												</td>
												<td className={cx(TD, MONO, MUTED)}>{param.default ?? '—'}</td>
											</tr>
										))}
									</tbody>
								</table>
							</div>
						</Section>
					)}

					{parsed.metrics.length > 0 && (
						<Section
							label={
								<>
									<Layers size={12} />
									Metrics
									<span className={COUNT}>({parsed.metrics.length})</span>
								</>
							}
						>
							{parsed.metrics.some((m) => m.expr) ? (
								<div className={TABLE_WRAP}>
									<table className={TABLE}>
										<thead>
											<tr>
												<th className={TH}>Name</th>
												<th className={TH}>Expression</th>
											</tr>
										</thead>
										<tbody className="[&_tr:last-child_td]:border-b-0">
											{parsed.metrics.map((metric) => (
												<tr key={metric.name}>
													<td className={cx(TD, 'font-medium')}>{metric.name}</td>
													<td className={cx(TD, MONO, MUTED)}>{metric.expr ?? '—'}</td>
												</tr>
											))}
										</tbody>
									</table>
								</div>
							) : (
								<div className="flex flex-wrap gap-1">
									{parsed.metrics.map((metric) => (
										<span key={metric.name} className={PILL}>
											{metric.name}
										</span>
									))}
								</div>
							)}
						</Section>
					)}

					{parsed.dimensions.length > 0 && (
						<Section
							label={
								<>
									<Tag size={12} />
									Dimensions
									<span className={COUNT}>({parsed.dimensions.length})</span>
								</>
							}
						>
							{parsed.dimensions.some((d) => d.expr) ? (
								<div className={TABLE_WRAP}>
									<table className={TABLE}>
										<thead>
											<tr>
												<th className={TH}>Label</th>
												<th className={TH}>Column</th>
											</tr>
										</thead>
										<tbody className="[&_tr:last-child_td]:border-b-0">
											{parsed.dimensions.map((dim) => (
												<tr key={dim.key}>
													<td className={cx(TD, 'font-medium')}>{dim.label}</td>
													<td className={cx(TD, MONO, MUTED)}>{dim.expr ?? '—'}</td>
												</tr>
											))}
										</tbody>
									</table>
								</div>
							) : (
								<div className="flex flex-wrap gap-1">
									{parsed.dimensions.map((dim) => (
										<span key={dim.key} className={PILL}>
											{dim.label}
										</span>
									))}
								</div>
							)}
						</Section>
					)}

					{parsed.filters.length > 0 && (
						<Section
							label={
								<>
									<Filter size={12} />
									Filters
									<span className={COUNT}>({parsed.filters.length})</span>
								</>
							}
						>
							<div className="flex flex-wrap gap-1">
								{parsed.filters.map((filter) => (
									<span key={filter} className={PILL}>
										{stripNounPrefix(filter)}
									</span>
								))}
							</div>
						</Section>
					)}

					{parsed.comments.length > 0 && (
						<Section
							label={
								<>
									<FileText size={12} />
									Details
								</>
							}
						>
							<div className="flex flex-col gap-1">
								{parsed.comments.map((comment, i) => (
									<div className="flex gap-2 text-[12px]" key={i}>
										<span className="flex-shrink-0 font-medium text-text-3">{comment.key}</span>
										<span className={MUTED}>{comment.value}</span>
									</div>
								))}
							</div>
						</Section>
					)}
				</div>
			)}

			{showSource && (
				<div className="mt-4 flex min-h-0 flex-1 flex-col overflow-hidden rounded-xs border border-line">
					<div className="flex-shrink-0 border-b border-line bg-ink/3 px-3 py-1.5 text-[10px] font-semibold tracking-[0.05em] text-muted uppercase">
						Source
					</div>
					<PierreCode fileName={filePath || 'file.tql'} contents={content} lang="sql" fill />
				</div>
			)}
		</div>
	);
}
