// examples/react-demo/src/primitives/Select.tsx
import { Check, ChevronDown, Search } from 'lucide-react';
import { useCallback, useEffect, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';

import { cx } from '../lib/cx';
import type { SelectOption } from './selectTypes';

type Props<T extends string | number> = {
	/** Selected value. */
	value: T;
	options: SelectOption<T>[];
	placeholder?: string;
	disabled?: boolean;
	/** Show a search box inside the popover to filter options by label. */
	searchable?: boolean;
	searchPlaceholder?: string;
	onValueChange?: (value: T) => void;
	className?: string;
	id?: string;
	'aria-label'?: string;
	/** Optional content rendered before the value inside the trigger. */
	leading?: ReactNode;
};

type Placement = 'bottom' | 'top';

const ICON = 'size-4 shrink-0 rounded-[3px] object-contain';

export function Select<T extends string | number>({
	value,
	options,
	placeholder = 'Select…',
	disabled = false,
	searchable = false,
	searchPlaceholder = 'Search…',
	onValueChange,
	className = '',
	id,
	'aria-label': ariaLabel,
	leading
}: Props<T>) {
	const [open, setOpen] = useState(false);
	const [query, setQuery] = useState('');
	const [activeIndex, setActiveIndex] = useState(-1);
	const [pos, setPos] = useState({
		left: 0,
		top: 0,
		width: 0,
		maxHeight: 260,
		placement: 'bottom' as Placement
	});

	const triggerRef = useRef<HTMLButtonElement | null>(null);
	const popoverRef = useRef<HTMLDivElement | null>(null);
	const listRef = useRef<HTMLDivElement | null>(null);
	const searchRef = useRef<HTMLInputElement | null>(null);

	const selected = options.find((option) => option.value === value);
	const q = query.trim().toLowerCase();
	const filteredOptions =
		!searchable || !q ? options : options.filter((option) => option.label.toLowerCase().includes(q));

	const place = useCallback(() => {
		const el = triggerRef.current;
		if (!el) return;
		const rect = el.getBoundingClientRect();
		const margin = 8;
		const gap = 4;
		const spaceBelow = window.innerHeight - rect.bottom - gap - margin;
		const spaceAbove = rect.top - gap - margin;
		// Prefer opening downward unless there's meaningfully more room above.
		const placement: Placement = spaceBelow >= 220 || spaceBelow >= spaceAbove ? 'bottom' : 'top';
		const available = placement === 'bottom' ? spaceBelow : spaceAbove;
		setPos({
			left: rect.left,
			width: rect.width,
			top: placement === 'bottom' ? rect.bottom + gap : rect.top - gap,
			maxHeight: Math.max(140, Math.min(320, available)),
			placement
		});
	}, []);

	function openMenu() {
		if (disabled) return;
		setQuery('');
		place();
		const current = options.findIndex((option) => option.value === value);
		setActiveIndex(current >= 0 ? current : 0);
		setOpen(true);
	}

	const closeMenu = useCallback(() => {
		setOpen(false);
		setActiveIndex(-1);
		setQuery('');
	}, []);

	function toggle() {
		if (open) closeMenu();
		else openMenu();
	}

	function choose(option: SelectOption<T> | undefined) {
		if (!option || option.disabled) return;
		onValueChange?.(option.value);
		closeMenu();
		triggerRef.current?.focus();
	}

	function step(delta: number) {
		const count = filteredOptions.length;
		if (count === 0) return;
		let next = activeIndex < 0 ? (delta > 0 ? -1 : 0) : activeIndex;
		for (let i = 0; i < count; i += 1) {
			next = (next + delta + count) % count;
			if (!filteredOptions[next]?.disabled) break;
		}
		setActiveIndex(next);
	}

	/** Navigation keys shared by the trigger and the search box. */
	function onMenuNavKeydown(event: React.KeyboardEvent): boolean {
		switch (event.key) {
			case 'Escape':
				event.preventDefault();
				closeMenu();
				triggerRef.current?.focus();
				return true;
			case 'ArrowDown':
				event.preventDefault();
				step(1);
				return true;
			case 'ArrowUp':
				event.preventDefault();
				step(-1);
				return true;
			case 'Home':
				event.preventDefault();
				setActiveIndex(0);
				return true;
			case 'End':
				event.preventDefault();
				setActiveIndex(filteredOptions.length - 1);
				return true;
			case 'Enter':
				event.preventDefault();
				choose(filteredOptions[activeIndex]);
				return true;
			case 'Tab':
				closeMenu();
				return true;
		}
		return false;
	}

	function onTriggerKeydown(event: React.KeyboardEvent) {
		if (disabled) return;
		if (!open) {
			if (
				event.key === 'ArrowDown' ||
				event.key === 'ArrowUp' ||
				event.key === 'Enter' ||
				event.key === ' '
			) {
				event.preventDefault();
				openMenu();
			}
			return;
		}
		// When not searchable the trigger keeps focus, so it drives navigation.
		if (event.key === ' ') {
			event.preventDefault();
			choose(filteredOptions[activeIndex]);
			return;
		}
		onMenuNavKeydown(event);
	}

	// Dismiss on any pointer press outside the trigger + popover.
	useEffect(() => {
		if (!open) return;
		const onPointerDown = (event: PointerEvent) => {
			const target = event.target;
			if (
				target instanceof Node &&
				(triggerRef.current?.contains(target) || popoverRef.current?.contains(target))
			) {
				return;
			}
			closeMenu();
		};
		window.addEventListener('pointerdown', onPointerDown);
		return () => window.removeEventListener('pointerdown', onPointerDown);
	}, [open, closeMenu]);

	// Keep the popover glued to the trigger while it's open.
	useEffect(() => {
		if (!open) return;
		const handler = () => place();
		window.addEventListener('scroll', handler, true);
		window.addEventListener('resize', handler);
		return () => {
			window.removeEventListener('scroll', handler, true);
			window.removeEventListener('resize', handler);
		};
	}, [open, place]);

	// Keep the highlighted option in view during keyboard navigation.
	useLayoutEffect(() => {
		if (!open || activeIndex < 0 || !listRef.current) return;
		const el = listRef.current.children[activeIndex];
		if (el instanceof HTMLElement) el.scrollIntoView({ block: 'nearest' });
	}, [open, activeIndex]);

	// Focus the search box as soon as the popover opens.
	useEffect(() => {
		if (open && searchable) searchRef.current?.focus();
	}, [open, searchable]);

	// Keep the highlight valid as the filtered list changes while typing.
	useEffect(() => {
		const count = filteredOptions.length;
		if (activeIndex > count - 1) setActiveIndex(count > 0 ? 0 : -1);
	}, [filteredOptions.length, activeIndex]);

	return (
		<>
			<button
				ref={triggerRef}
				id={id}
				type="button"
				disabled={disabled}
				className={cx(
					'inline-flex w-full cursor-pointer items-center gap-2 rounded-sm border bg-elevate/78 px-[11px] py-[9px] text-left text-[13px] leading-[1.4] text-ink transition-[border-color,background] duration-[120ms] ease-[ease]',
					'hover:not-disabled:bg-elevate/92 focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-accent/55',
					'disabled:cursor-not-allowed disabled:opacity-60',
					open ? 'border-accent/55' : 'border-line/85',
					className
				)}
				aria-haspopup="listbox"
				aria-expanded={open}
				aria-label={ariaLabel}
				onClick={toggle}
				onKeyDown={onTriggerKeydown}
			>
				{leading && <span className="inline-flex shrink-0 items-center text-muted">{leading}</span>}
				{selected?.iconSrc && <img className={ICON} src={selected.iconSrc} alt="" />}
				<span
					className={cx(
						'min-w-0 flex-1 overflow-hidden text-ellipsis whitespace-nowrap',
						!selected && 'text-muted'
					)}
				>
					{selected ? selected.label : placeholder}
				</span>
				<ChevronDown
					className={cx(
						'shrink-0 text-muted transition-transform duration-150 ease-[ease] motion-reduce:transition-none',
						open && 'rotate-180'
					)}
					size={15}
					strokeWidth={2}
					aria-hidden="true"
				/>
			</button>

			{open &&
				createPortal(
					<div
						ref={popoverRef}
						className={cx(
							'fixed z-[1000] flex min-h-0 animate-select-in flex-col rounded-sm border border-line/85 bg-[color-mix(in_srgb,var(--color-paper)_96%,var(--color-elevate))] p-1 shadow-[0_12px_32px_rgba(15,15,20,0.12)] motion-reduce:animate-none',
							pos.placement === 'top' ? 'origin-bottom -translate-y-full' : 'origin-top'
						)}
						style={{
							left: `${pos.left}px`,
							top: `${pos.top}px`,
							minWidth: `${pos.width}px`,
							maxHeight: `${pos.maxHeight}px`
						}}
					>
						{searchable && (
							<div className="mb-1 flex shrink-0 items-center gap-1.5 rounded-[7px] bg-line/30 px-2 py-1.5 text-muted">
								<Search size={14} strokeWidth={2} aria-hidden="true" />
								<input
									ref={searchRef}
									className="min-w-0 flex-1 border-0 bg-transparent p-0 text-[13px] text-ink focus:outline-none"
									type="text"
									autoComplete="off"
									spellCheck={false}
									placeholder={searchPlaceholder}
									aria-label={searchPlaceholder}
									value={query}
									onChange={(event) => setQuery(event.target.value)}
									onKeyDown={onMenuNavKeydown}
								/>
							</div>
						)}

						<div
							ref={listRef}
							className="flex min-h-0 flex-col gap-px overflow-y-auto"
							role="listbox"
							aria-label={ariaLabel}
						>
							{filteredOptions.length === 0 ? (
								<p className="m-0 px-2 py-2.5 text-center text-[12.5px] text-muted">No matches.</p>
							) : (
								filteredOptions.map((option, index) => (
									<button
										key={String(option.value)}
										type="button"
										role="option"
										aria-selected={option.value === value}
										className={cx(
											'flex w-full cursor-pointer items-center gap-2 rounded-[7px] border-0 px-2 py-[7px] text-left text-[13px] text-ink disabled:cursor-not-allowed disabled:opacity-50',
											index === activeIndex ? 'bg-accent/12' : 'bg-transparent',
											option.value === value && 'font-medium'
										)}
										disabled={option.disabled}
										onMouseEnter={() => setActiveIndex(index)}
										onClick={() => choose(option)}
									>
										{option.iconSrc && <img className={ICON} src={option.iconSrc} alt="" />}
										<span className="flex min-w-0 flex-1 flex-col gap-px">
											<span className="overflow-hidden text-ellipsis whitespace-nowrap">
												{option.label}
											</span>
											{option.hint && (
												<span className="text-[11.5px] leading-[1.3] text-muted">{option.hint}</span>
											)}
										</span>
										{option.value === value && (
											<span className="inline-flex shrink-0 text-accent" aria-hidden="true">
												<Check size={14} strokeWidth={2.25} />
											</span>
										)}
									</button>
								))
							)}
						</div>
					</div>,
					document.body
				)}
		</>
	);
}

// examples/admin-view/src/lib/primitives/Select.svelte
<script lang="ts">
	import { Check, ChevronDown, Search } from "@lucide/svelte";
	import type { Snippet } from "svelte";
	import type { SelectOption } from "./types";

	let {
		value = $bindable(),
		options,
		placeholder = "Select…",
		disabled = false,
		searchable = false,
		searchPlaceholder = "Search…",
		onValueChange,
		class: className = "",
		id,
		label,
		leading,
	}: {
		value: string | number;
		options: SelectOption[];
		placeholder?: string;
		disabled?: boolean;
		searchable?: boolean;
		searchPlaceholder?: string;
		onValueChange?: (value: string | number) => void;
		class?: string;
		id?: string;
		label?: string;
		leading?: Snippet;
	} = $props();

	let open = $state(false);
	let query = $state("");
	let activeIndex = $state(-1);
	let root: HTMLDivElement;
	let trigger = $state<HTMLButtonElement>();
	let searchInput = $state<HTMLInputElement>();
	let list = $state<HTMLDivElement>();
	let placement = $state("");
	const selected = $derived(options.find((option) => option.value === value));
	const filtered = $derived(
		options.filter(
			(option) =>
				!query.trim() ||
				option.label.toLowerCase().includes(query.trim().toLowerCase()),
		),
	);

	$effect(() => {
		if (!open || typeof window === "undefined") return;
		const outside = (event: PointerEvent) => {
			if (event.target instanceof Node && !root.contains(event.target))
				close();
		};
		window.addEventListener("pointerdown", outside);
		window.addEventListener("resize", place);
		window.addEventListener("scroll", place, true);
		return () => {
			window.removeEventListener("pointerdown", outside);
			window.removeEventListener("resize", place);
			window.removeEventListener("scroll", place, true);
		};
	});

	$effect(() => {
		if (open && searchable) queueMicrotask(() => searchInput?.focus());
	});

	$effect(() => {
		if (!open || activeIndex < 0) return;
		list?.children[activeIndex]?.scrollIntoView({ block: "nearest" });
	});

	function place(): void {
		if (!trigger) return;
		const rect = trigger.getBoundingClientRect();
		const width = Math.min(
			Math.max(rect.width, 220),
			Math.max(220, window.innerWidth - 16),
		);
		const left = Math.min(
			Math.max(8, rect.right - width),
			window.innerWidth - width - 8,
		);
		const below = window.innerHeight - rect.bottom - 12;
		const above = rect.top - 12;
		const flip = below < Math.min(220, above);
		placement =
			`left:${Math.round(left)}px;width:${Math.round(width)}px;` +
			`max-height:${Math.round(Math.min(300, flip ? above : below))}px;` +
			(flip
				? `bottom:${Math.round(window.innerHeight - rect.top + 4)}px;`
				: `top:${Math.round(rect.bottom + 4)}px;`);
	}

	function show(): void {
		if (disabled) return;
		place();
		query = "";
		activeIndex = Math.max(
			0,
			options.findIndex((option) => option.value === value),
		);
		open = true;
	}

	function close(): void {
		open = false;
		query = "";
		activeIndex = -1;
	}
	function choose(option: SelectOption | undefined): void {
		if (!option || option.disabled) return;
		value = option.value;
		onValueChange?.(value);
		close();
	}

	function step(delta: number): void {
		if (!filtered.length) return;
		let next = activeIndex;
		for (let i = 0; i < filtered.length; i += 1) {
			next = (next + delta + filtered.length) % filtered.length;
			if (!filtered[next]?.disabled) break;
		}
		activeIndex = next;
	}

	function keydown(event: KeyboardEvent): void {
		if (
			!open &&
			["ArrowDown", "ArrowUp", "Enter", " "].includes(event.key)
		) {
			event.preventDefault();
			show();
			return;
		}
		if (!open) return;
		if (event.key === "Escape") {
			event.preventDefault();
			close();
		} else if (event.key === "ArrowDown") {
			event.preventDefault();
			step(1);
		} else if (event.key === "ArrowUp") {
			event.preventDefault();
			step(-1);
		} else if (event.key === "Home") {
			event.preventDefault();
			activeIndex = 0;
		} else if (event.key === "End") {
			event.preventDefault();
			activeIndex = filtered.length - 1;
		} else if (
			event.key === "Enter" ||
			(!searchable && event.key === " ")
		) {
			event.preventDefault();
			choose(filtered[activeIndex]);
		} else if (event.key === "Tab") close();
	}
</script>

<div class={`select-root ${className}`} bind:this={root}>
	<button
		bind:this={trigger}
		{id}
		class:open
		type="button"
		{disabled}
		aria-haspopup="listbox"
		aria-expanded={open}
		aria-label={label}
		onclick={() => (open ? close() : show())}
		onkeydown={keydown}
	>
		{#if leading}<span class="leading">{@render leading()}</span>{/if}
		{#if selected?.iconSrc}<img src={selected.iconSrc} alt="" />{/if}
		<span class:placeholder={!selected} class="value"
			>{selected?.label ?? placeholder}</span
		>
		<ChevronDown size={15} class={open ? "rotate" : ""} />
	</button>
	{#if open}
		<div class="popover" style={placement}>
			{#if searchable}
				<div class="search">
					<Search size={14} /><input
						bind:this={searchInput}
						bind:value={query}
						placeholder={searchPlaceholder}
						aria-label={searchPlaceholder}
						onkeydown={keydown}
					/>
				</div>
			{/if}
			<div
				class="options"
				role="listbox"
				aria-label={label}
				bind:this={list}
			>
				{#if !filtered.length}<p>No matches.</p>{/if}
				{#each filtered as option, index (option.value)}
					<button
						type="button"
						role="option"
						aria-selected={option.value === value}
						class:active={index === activeIndex}
						class:selected={option.value === value}
						disabled={option.disabled}
						onpointerenter={() => (activeIndex = index)}
						onclick={() => choose(option)}
					>
						{#if option.iconSrc}<img
								src={option.iconSrc}
								alt=""
							/>{/if}
						<span class="option-text">
							<span class="option-line">
								<strong>{option.label}</strong>
								{#if option.meta}<em>{option.meta}</em>{/if}
							</span>
							{#if option.hint}<small>{option.hint}</small>{/if}
						</span>
						<Check
							size={13}
							class={option.value === value ? "" : "hidden-check"}
						/>
					</button>
				{/each}
			</div>
		</div>
	{/if}
</div>

<style>
	.select-root {
		position: relative;
		width: 100%;
	}
	.select-root > button {
		display: inline-flex;
		width: 100%;
		align-items: center;
		gap: 8px;
		border: 1px solid color-mix(in srgb, var(--color-line) 85%, transparent);
		border-radius: 10px;
		background: color-mix(in srgb, var(--color-elevate) 78%, transparent);
		padding: 9px 11px;
		color: var(--color-ink);
		font-size: 13px;
		line-height: 1.4;
		text-align: left;
		cursor: pointer;
	}
	.select-root > button:hover:not(:disabled) {
		background: color-mix(in srgb, var(--color-elevate) 92%, transparent);
	}
	.select-root > button.open {
		border-color: color-mix(in srgb, var(--color-accent) 55%, transparent);
	}
	.select-root > button:disabled {
		cursor: not-allowed;
		opacity: 0.6;
	}
	.leading {
		display: inline-flex;
		flex: 0 0 auto;
		color: var(--color-muted);
	}
	.value {
		min-width: 0;
		flex: 1;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.placeholder {
		color: var(--color-muted);
	}
	img {
		width: 16px;
		height: 16px;
		flex: 0 0 auto;
		border-radius: 3px;
		object-fit: contain;
	}
	:global(.rotate) {
		transform: rotate(180deg);
	}
	/* Right-anchored to the trigger by place(), so a popover wider than a narrow
	   trigger grows inward instead of spilling past the panel edge beside it. */
	.popover {
		position: fixed;
		z-index: 1000;
		display: flex;
		flex-direction: column;
		border: 1px solid color-mix(in srgb, var(--color-line) 85%, transparent);
		border-radius: 10px;
		background: var(--color-elevate);
		padding: 4px;
		box-shadow:
			0 10px 30px rgba(15, 15, 20, 0.1),
			0 1px 2px rgba(15, 15, 20, 0.06);
	}
	.search {
		display: flex;
		align-items: center;
		gap: 6px;
		margin: -4px -4px 4px;
		border-bottom: 1px solid
			color-mix(in srgb, var(--color-line) 70%, transparent);
		padding: 8px 10px;
		color: var(--color-muted);
	}
	.search input {
		min-width: 0;
		flex: 1;
		border: 0;
		outline: 0;
		background: transparent;
		padding: 0;
		color: var(--color-ink);
		font-size: 12.5px;
	}
	.search input::placeholder {
		color: var(--color-muted);
	}
	.options {
		min-height: 0;
		overflow-y: auto;
		overscroll-behavior: contain;
	}
	.options > button {
		display: flex;
		width: 100%;
		align-items: center;
		gap: 8px;
		border: 0;
		border-radius: 6px;
		background: transparent;
		padding: 5px 7px;
		color: var(--color-ink);
		font-size: 12.5px;
		line-height: 1.35;
		text-align: left;
		cursor: pointer;
	}
	.options > button.active {
		background: color-mix(in srgb, var(--color-line) 45%, transparent);
	}
	.options > button:disabled {
		cursor: not-allowed;
		opacity: 0.5;
	}
	.options > button :global(svg) {
		flex: 0 0 auto;
		color: var(--color-accent);
	}
	.options > button :global(.hidden-check) {
		visibility: hidden;
	}
	.option-text {
		min-width: 0;
		flex: 1;
	}
	.option-line {
		display: flex;
		align-items: baseline;
		gap: 8px;
	}
	.options strong,
	.options small {
		display: block;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.options strong {
		min-width: 0;
		flex: 1;
		font-weight: 400;
	}
	.options > button.selected strong {
		font-weight: 500;
	}
	.options em {
		flex: 0 0 auto;
		color: var(--color-muted);
		font-size: 11.5px;
		font-style: normal;
		font-variant-numeric: tabular-nums;
	}
	.options small {
		margin-top: 1px;
		color: var(--color-muted);
		font-size: 11.5px;
	}
	.options p {
		margin: 0;
		padding: 10px 8px;
		color: var(--color-muted);
		font-size: 12.5px;
		text-align: center;
	}
</style>
