// examples/admin-view/src/lib/primitives/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { ButtonSize, ButtonVariant } from './types';

	let {
		variant = 'solid',
		size = 'md',
		href,
		disabled = false,
		class: className = '',
		type = 'button',
		children,
		...rest
	}: {
		variant?: ButtonVariant;
		size?: ButtonSize;
		href?: string;
		disabled?: boolean;
		class?: string;
		type?: 'button' | 'submit' | 'reset';
		children?: Snippet;
		[key: string]: unknown;
	} = $props();
</script>

{#if href && !disabled}
	<a {href} class={`primitive-button ${className}`} data-variant={variant} data-size={size} {...rest}>
		{@render children?.()}
	</a>
{:else}
	<button {type} {disabled} class={`primitive-button ${className}`} data-variant={variant} data-size={size} {...rest}>
		{@render children?.()}
	</button>
{/if}

<style>
	.primitive-button { display: inline-flex; align-items: center; justify-content: center; gap: 6px; border: 0; border-radius: 12px; font-family: var(--font-sans); font-weight: 500; line-height: 1.25; text-decoration: none; white-space: nowrap; cursor: pointer; user-select: none; transition: color 120ms ease, background 120ms ease, border-color 120ms ease, box-shadow 120ms ease, opacity 120ms ease; }
	.primitive-button:disabled { cursor: not-allowed; opacity: .5; }
	.primitive-button[data-size='xs'] { padding: 2px 8px; font-size: 10px; }
	.primitive-button[data-size='sm'] { padding: 4px 10px; font-size: 12px; }
	.primitive-button[data-size='md'] { padding: 6px 12px; font-size: 12px; }
	.primitive-button[data-size='lg'] { padding: 8px 16px; font-size: 14px; }
	.primitive-button[data-size='xl'] { padding: 10px 20px; font-size: 16px; }
	.primitive-button[data-variant='solid'] { background: var(--color-accent); color: var(--color-paper); }
	.primitive-button[data-variant='solid']:hover { opacity: .9; }
	.primitive-button[data-variant='classic'] { background: var(--color-accent); color: var(--color-paper); box-shadow: inset 0 1px 0 rgba(255,255,255,.35), 0 2px 4px -1px rgba(10,10,10,.45); }
	.primitive-button[data-variant='classic']:hover { box-shadow: inset 0 1px 0 rgba(255,255,255,.35), 0 3px 6px -1px rgba(10,10,10,.5); }
	.primitive-button[data-variant='classic']:active { transform: translateY(1px); }
	.primitive-button[data-variant='soft'] { background: color-mix(in srgb, var(--color-accent) 10%, transparent); color: var(--color-accent); }
	.primitive-button[data-variant='soft']:hover { background: color-mix(in srgb, var(--color-accent) 20%, transparent); }
	.primitive-button[data-variant='surface'] { border: 1px solid var(--color-line); background: var(--color-paper); color: var(--color-ink); }
	.primitive-button[data-variant='surface']:hover { border-color: var(--color-accent); color: var(--color-accent); }
	.primitive-button[data-variant='outline'] { border: 1px solid var(--color-accent); background: transparent; color: var(--color-accent); }
	.primitive-button[data-variant='outline']:hover { background: color-mix(in srgb, var(--color-accent) 10%, transparent); }
	.primitive-button[data-variant='ghost'] { background: transparent; color: var(--color-muted); }
	.primitive-button[data-variant='ghost']:hover { background: color-mix(in srgb, var(--color-line) 40%, transparent); color: var(--color-accent); }
	.primitive-button[data-variant='danger'] { background: #dc2626; color: var(--color-paper); }
	.primitive-button[data-variant='danger']:hover { background: #b91c1c; }
	.primitive-button[data-variant='danger-soft'] { background: rgba(239,68,68,.1); color: #dc2626; }
	.primitive-button[data-variant='danger-soft']:hover { background: rgba(239,68,68,.2); }
</style>

// examples/react-demo/src/primitives/Button.tsx
import type { AnchorHTMLAttributes, ButtonHTMLAttributes, ReactNode } from 'react';

type Variant =
	| 'solid'
	| 'classic'
	| 'soft'
	| 'surface'
	| 'outline'
	| 'ghost'
	| 'danger'
	| 'danger-soft';
type Size = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

type CommonProps = {
	variant?: Variant;
	size?: Size;
	href?: string;
	disabled?: boolean;
	className?: string;
	children?: ReactNode;
};

type Props = CommonProps &
	Omit<ButtonHTMLAttributes<HTMLButtonElement> & AnchorHTMLAttributes<HTMLAnchorElement>, 'className'>;

const base =
	'inline-flex select-none items-center justify-center gap-1.5 rounded-md font-sans whitespace-nowrap transition-colors focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-accent disabled:cursor-not-allowed disabled:opacity-50';

const sizes: Record<Size, string> = {
	xs: 'px-2 py-0.5 text-[10px]',
	sm: 'px-2.5 py-1 text-xs',
	md: 'px-3 py-1.5 text-xs',
	lg: 'px-4 py-2 text-sm',
	xl: 'px-5 py-2.5 text-base'
};

const variants: Record<Variant, string> = {
	solid: 'bg-accent text-paper hover:opacity-90',
	// Raised/embossed: inner top highlight + drop shadow, lifts on hover.
	classic:
		'bg-accent text-paper shadow-[inset_0_1px_0_0_rgba(255,255,255,0.35),0_2px_4px_-1px_rgba(10,10,10,0.45)] hover:shadow-[inset_0_1px_0_0_rgba(255,255,255,0.35),0_3px_6px_-1px_rgba(10,10,10,0.5)] active:translate-y-px active:shadow-[inset_0_1px_2px_0_rgba(10,10,10,0.4)]',
	soft: 'bg-accent/10 text-accent hover:bg-accent/20',
	surface: 'border border-line bg-paper text-ink hover:border-accent hover:text-accent',
	outline: 'border border-accent text-accent hover:bg-accent/10',
	ghost: 'text-muted hover:bg-line/40 hover:text-accent',
	// Destructive: solid red for confirm-to-delete style actions.
	danger: 'bg-red-600 text-paper hover:bg-red-700',
	'danger-soft': 'bg-red-500/10 text-red-600 hover:bg-red-500/20'
};

export function Button({
	variant = 'solid',
	size = 'md',
	href,
	disabled = false,
	className = '',
	children,
	...rest
}: Props) {
	const cls = `${base} ${sizes[size]} ${variants[variant]} ${className}`;

	// A disabled link isn't inert, so fall back to a real disabled <button>.
	if (href && !disabled) {
		return (
			<a href={href} className={cls} {...(rest as AnchorHTMLAttributes<HTMLAnchorElement>)}>
				{children}
			</a>
		);
	}

	return (
		<button
			type="button"
			disabled={disabled}
			className={cls}
			{...(rest as ButtonHTMLAttributes<HTMLButtonElement>)}
		>
			{children}
		</button>
	);
}
