// examples/admin-view/src/lib/primitives/Modal.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	let { open = $bindable(false), title, dismissable = true, onClose, children, actions }: {
		open?: boolean; title?: string; dismissable?: boolean; onClose?: () => void; children?: Snippet; actions?: Snippet;
	} = $props();
	function dismiss(): void { if (!dismissable) return; open = false; onClose?.(); }
	function keydown(event: KeyboardEvent): void { if (open && event.key === 'Escape') dismiss(); }
</script>

<svelte:window onkeydown={keydown} />
{#if open}
	<div class="modal-root" role="dialog" aria-modal="true" aria-label={title}>
		<button class="backdrop" type="button" aria-label="Close" tabindex="-1" onclick={dismiss}></button>
		<div class="dialog">
			{#if title}<h2>{title}</h2>{/if}
			{#if children}<div class="body">{@render children()}</div>{/if}
			{#if actions}<div class="actions">{@render actions()}</div>{/if}
		</div>
	</div>
{/if}

<style>
	.modal-root { position: fixed; z-index: 1100; inset: 0; display: flex; align-items: center; justify-content: center; padding: 16px; }
	.backdrop { position: absolute; inset: 0; border: 0; background: rgba(26,26,28,.4); padding: 0; cursor: default; backdrop-filter: blur(2px); animation: fade 160ms ease; }
	.dialog { position: relative; z-index: 1; width: 100%; max-width: 320px; border: 1px solid var(--color-line); border-radius: 16px; background: var(--color-paper); padding: 12px 16px; box-shadow: 0 20px 60px -12px rgba(15,15,20,.18); animation: reveal 180ms cubic-bezier(.33,1,.68,1); }
	h2 { margin: 0; color: var(--color-ink); font-size: 16px; font-weight: 500; line-height: 1.25; }
	.body { margin-top: 6px; color: var(--color-muted); font-size: 14px; line-height: 1.625; }
	.actions { display: flex; justify-content: flex-end; gap: 8px; margin-top: 16px; }
	@keyframes fade { from { opacity: 0; } }
	@keyframes reveal { from { opacity: 0; transform: translateY(6px) scale(.97); } }
	@media (prefers-reduced-motion: reduce) { .backdrop,.dialog { animation: none; } }
</style>

// examples/react-demo/src/primitives/Modal.tsx
import { useEffect, type ReactNode } from 'react';

type Props = {
	open?: boolean;
	title?: string;
	/** Body content. */
	children?: ReactNode;
	/**
	 * Footer buttons. Convention: pass the dismiss/secondary button FIRST and
	 * the primary action LAST — the row is right-aligned, so the primary action
	 * sits on the right and the dismiss to its left.
	 */
	actions?: ReactNode;
	/** Called when dismissed via backdrop or Escape (not on programmatic close). */
	onClose?: () => void;
	/** Toggle the bindable open state (Svelte's `bind:open` equivalent). */
	onOpenChange?: (open: boolean) => void;
	/** Allow clicking the backdrop to dismiss. */
	dismissable?: boolean;
};

export function Modal({
	open = false,
	title,
	children,
	actions,
	onClose,
	onOpenChange,
	dismissable = true
}: Props) {
	useEffect(() => {
		if (!open || !dismissable) return;
		const onKeydown = (event: KeyboardEvent) => {
			if (event.key === 'Escape') {
				onOpenChange?.(false);
				onClose?.();
			}
		};
		window.addEventListener('keydown', onKeydown);
		return () => window.removeEventListener('keydown', onKeydown);
	}, [open, dismissable, onClose, onOpenChange]);

	if (!open) return null;

	const dismiss = () => {
		onOpenChange?.(false);
		onClose?.();
	};

	return (
		<div
			className="fixed inset-0 z-[100] flex items-center justify-center p-4"
			role="dialog"
			aria-modal="true"
			aria-label={title}
		>
			<button
				type="button"
				className="absolute inset-0 animate-modal-fade cursor-default border-0 bg-ink/40 p-0 backdrop-blur-xs motion-reduce:animate-none"
				onClick={() => dismissable && dismiss()}
				aria-label="Close"
				tabIndex={-1}
			/>

			<div className="relative z-10 w-full max-w-xs animate-modal-reveal rounded-lg border border-line bg-paper px-4 py-3 shadow-[0_20px_60px_-12px_rgba(15,15,20,0.18)] [will-change:transform,opacity] motion-reduce:animate-none">
				{title && (
					<h2 className="font-sans text-base font-medium leading-tight text-ink">{title}</h2>
				)}
				{children && (
					<div className="mt-1.5 font-sans text-sm leading-relaxed text-muted">{children}</div>
				)}
				{actions && (
					// Right-aligned: dismiss (first) on the left, primary action (last)
					// on the right.
					<div className="mt-4 flex justify-end gap-2">{actions}</div>
				)}
			</div>
		</div>
	);
}
