// examples/admin-view/src/lib/primitives/Switch.svelte
<script lang="ts">
	let { checked = $bindable(false), disabled = false, onCheckedChange, label, type = 'button' }: {
		checked?: boolean;
		disabled?: boolean;
		onCheckedChange?: (checked: boolean) => void;
		label?: string;
		type?: 'button' | 'submit';
	} = $props();

	function toggle(): void {
		if (disabled) return;
		checked = !checked;
		onCheckedChange?.(checked);
	}
</script>

<button {type} role="switch" aria-checked={checked} aria-label={label} {disabled} data-checked={checked ? '' : undefined} onclick={toggle}>
	<span data-checked={checked ? '' : undefined}></span>
</button>

<style>
	button { display: inline-flex; width: 36px; height: 20px; flex: 0 0 auto; align-items: center; border: 1px solid var(--color-line); border-radius: 999px; outline: none; background: var(--color-paper); padding: 2px; cursor: pointer; transition: background 150ms, border-color 150ms; }
	button[data-checked] { border-color: var(--color-accent); background: var(--color-accent); }
	button:disabled { cursor: default; opacity: .4; }
	span { width: 14px; height: 14px; border-radius: 999px; background: var(--color-ink); transition: transform 150ms, background 150ms; }
	span[data-checked] { transform: translateX(16px); background: var(--color-paper); }
</style>

// examples/react-demo/src/primitives/Switch.tsx
import type { ButtonHTMLAttributes } from 'react';

interface Props extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'> {
	/** On/off state. */
	checked?: boolean;
	/** Called with the new state when toggled. */
	onCheckedChange?: (checked: boolean) => void;
}

/**
 * Squared switch in the editorial palette: paper track + ink thumb that
 * inverts to an accent track + paper thumb when on.
 */
export function Switch({
	checked = false,
	onCheckedChange,
	disabled = false,
	className,
	...rest
}: Props) {
	function toggle() {
		if (disabled) return;
		onCheckedChange?.(!checked);
	}

	return (
		<button
			{...rest}
			type="button"
			role="switch"
			aria-checked={checked}
			disabled={disabled}
			data-checked={checked ? '' : undefined}
			onClick={toggle}
			className={`inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full border border-line bg-paper p-0.5 outline-none transition-colors duration-150 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent disabled:cursor-default disabled:opacity-40 data-[checked]:border-accent data-[checked]:bg-accent ${className ?? ''}`}
		>
			<span
				data-checked={checked ? '' : undefined}
				className="size-3.5 rounded-full bg-ink transition-[translate,background-color] duration-150 data-[checked]:translate-x-[18px] data-[checked]:bg-paper"
			/>
		</button>
	);
}
