// examples/react-demo/src/components/QuestionsCell.tsx
import { Check } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';

import { asRecords, asString, asStrings, getCellPayload, type CellLike } from '../lib/cells';
import { cx } from '../lib/cx';

// onAnswered lets the page re-attach its watch stream so the resumed run's
// cells show up (submitting halts → resumes the run on the backend).
type Props = { cell: CellLike; onAnswered?: () => void };

type Working = {
	selected: string[];
	custom: string;
	other: boolean;
	inputs: string[];
};

const blank = (q: Record<string, unknown>): Working => ({
	selected: [],
	custom: '',
	other: false,
	inputs: asRecords(q.inputs).map(() => '')
});

function kindOf(q: Record<string, unknown>): 'choice' | 'multichoice' | 'inputs' {
	const k = asString(q.kind);
	if (k.endsWith('MULTICHOICE')) return 'multichoice';
	if (k.endsWith('INPUTS')) return 'inputs';
	return 'choice';
}

function inputType(input: Record<string, unknown>): 'text' | 'multiline' | 'password' {
	if (input.sensitive === true) return 'password';
	return asString(input.kind).endsWith('MULTILINE') ? 'multiline' : 'text';
}

const HEAD =
	'flex items-center justify-between gap-2 text-[12px] font-semibold tracking-[0.01em] text-muted';
const DESC = 'm-0 text-[11.5px] not-italic text-muted';
/** Selectable card: neutral by default, accent border + tint when picked. */
const OPTION =
	'flex w-full cursor-pointer items-start gap-2 rounded-xs border px-[0.55rem] py-[0.4rem] text-left text-[12.5px] text-ink transition-[border-color,background] duration-[0.12s] focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-accent';
const TEXT_INPUT =
	'w-full rounded-xs border border-line bg-elevate px-[0.55rem] py-[0.35rem] text-[12.5px] text-ink focus-visible:border-transparent focus-visible:outline-2 focus-visible:-outline-offset-1 focus-visible:outline-accent';
const BTN_SUBMIT =
	'cursor-pointer rounded-xs border-0 bg-accent px-[0.85rem] py-[0.32rem] text-[12px] font-medium text-white transition-[background] duration-[0.12s] hover:bg-[color-mix(in_srgb,var(--color-accent)_88%,#000)] disabled:cursor-not-allowed disabled:opacity-50';
const BTN_SKIP =
	'cursor-pointer border-0 bg-transparent px-[0.3rem] py-[0.32rem] text-[12px] text-muted hover:text-ink disabled:cursor-not-allowed disabled:opacity-50';

/** Custom radio/checkbox indicator so the picked state reads clearly. */
function Indicator({ chosen, round }: { chosen: boolean; round: boolean }) {
	return (
		<span
			className={cx(
				'mt-px flex size-[15px] flex-none items-center justify-center border-[1.5px] text-white transition-[border-color,background] duration-[0.12s]',
				round ? 'rounded-full' : 'rounded-[4px]',
				chosen ? 'border-accent' : 'border-ink/25',
				chosen && (round ? 'bg-white' : 'bg-accent')
			)}
		>
			{chosen && (round ? <span className="size-[7px] rounded-full bg-accent" /> : <Check size={11} strokeWidth={3} />)}
		</span>
	);
}

export function QuestionsCell({ cell, onAnswered }: Props) {
	// Cell payloads arrive as untyped proto JSON; read them with the same
	// coercion helpers the rest of the demo uses (enums are string names).
	const payload = getCellPayload(cell);
	const status = asString(payload.status);
	const questions = asRecords(payload.questions);
	const summary = asRecords(payload.answers);
	const pending = status === '' || status.endsWith('PENDING');
	const dismissed = status.endsWith('DISMISSED');

	const [working, setWorking] = useState<Working[]>([]);
	const [submitting, setSubmitting] = useState(false);
	const [done, setDone] = useState(false); // optimistic: hide the form as soon as we submit
	const [step, setStep] = useState(0); // one-question-at-a-time cursor into `questions`
	const initId = useRef('');

	useEffect(() => {
		const id = asString(cell.id);
		const reset = id !== initId.current;
		if (reset) {
			initId.current = id;
			setStep(0);
		}
		setWorking((current) => {
			if (!reset && current.length === questions.length) return current;
			return questions.map((q, i) => (reset ? blank(q) : (current[i] ?? blank(q))));
		});
		// keep the cursor in range if the question set shrinks
		setStep((current) => (current > questions.length - 1 ? Math.max(0, questions.length - 1) : current));
	}, [cell.id, questions.length]);

	const isLast = step >= questions.length - 1;

	function patch(qi: number, next: Partial<Working>) {
		setWorking((current) => current.map((w, i) => (i === qi ? { ...w, ...next } : w)));
	}

	function pickChoice(qi: number, name: string) {
		patch(qi, { selected: [name], other: false });
	}

	function pickOther(qi: number, multi: boolean) {
		if (multi) {
			patch(qi, { other: !working[qi]?.other });
		} else {
			patch(qi, { selected: [], other: true });
		}
	}

	function toggleMulti(qi: number, name: string) {
		const set = new Set(working[qi]?.selected ?? []);
		if (set.has(name)) set.delete(name);
		else set.add(name);
		patch(qi, { selected: [...set] });
	}

	function setInput(qi: number, ii: number, value: string) {
		setWorking((current) =>
			current.map((w, i) =>
				i === qi ? { ...w, inputs: w.inputs.map((v, j) => (j === ii ? value : v)) } : w
			)
		);
	}

	function answerText(qi: number): string {
		const ans = summary[qi];
		const server = ans
			? [...asStrings(ans.selected), asString(ans.custom), ...asStrings(ans.inputs)].filter(Boolean)
			: [];
		if (server.length) return server.join(', ');
		const w = working[qi];
		if (!w) return '';
		const local = [...w.selected, w.other ? w.custom : '', ...w.inputs].filter(Boolean);
		return local.join(', ');
	}

	async function send(action: 'submit' | 'dismiss') {
		setSubmitting(true);
		try {
			const answers = working.map((w, i) => {
				const inputs = asRecords(questions[i]!.inputs);
				return {
					selected: w.selected,
					custom: w.other && w.custom ? w.custom : undefined,
					inputs: w.inputs,
					provided: inputs.map((_, j) => (w.inputs[j] ?? '').length > 0)
				};
			});
			const res = await fetch('/api/questions', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ action, cellId: asString(cell.id), answers })
			});
			if (!res.ok) {
				const body = (await res.json().catch(() => ({}))) as { error?: string };
				throw new Error(body.error ?? `Request failed (${res.status})`);
			}
			setDone(true);
			onAnswered?.();
			toast.success(action === 'submit' ? 'Answers submitted' : 'Questions skipped');
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to send answers.');
		} finally {
			setSubmitting(false);
		}
	}

	function renderQuestionCard(q: Record<string, unknown>, qi: number) {
		const kind = kindOf(q);
		const multi = kind === 'multichoice';

		return (
			<div className="flex flex-col gap-[0.35rem]">
				<p className="m-0 text-[13px] font-medium">{asString(q.question)}</p>
				{asString(q.explanation) && <p className={DESC}>{asString(q.explanation)}</p>}

				{kind === 'choice' || kind === 'multichoice' ? (
					<div className="flex flex-col gap-[0.3rem]">
						{asRecords(q.options).map((opt) => {
							const name = asString(opt.name);
							const chosen = working[qi]?.selected.includes(name) ?? false;
							return (
								<button
									key={name}
									type="button"
									className={cx(
										OPTION,
										chosen
											? 'border-accent bg-[color-mix(in_srgb,var(--color-accent)_8%,var(--color-elevate))]'
											: 'border-line bg-[color-mix(in_srgb,var(--color-paper)_60%,var(--color-elevate))] hover:border-[color-mix(in_srgb,var(--color-accent)_45%,var(--color-line))]'
									)}
									aria-pressed={chosen}
									onClick={() => (multi ? toggleMulti(qi, name) : pickChoice(qi, name))}
								>
									<Indicator chosen={chosen} round={!multi} />
									<span className="flex min-w-0 flex-col gap-[0.05rem]">
										<span className="font-[450]">{name}</span>
										{asString(opt.description) && (
											<span className={DESC}>{asString(opt.description)}</span>
										)}
									</span>
								</button>
							);
						})}
						{q.allowCustom === true && (
							<>
								<button
									type="button"
									className={cx(
										OPTION,
										working[qi]?.other
											? 'border-accent bg-[color-mix(in_srgb,var(--color-accent)_8%,var(--color-elevate))]'
											: 'border-line bg-[color-mix(in_srgb,var(--color-paper)_60%,var(--color-elevate))] hover:border-[color-mix(in_srgb,var(--color-accent)_45%,var(--color-line))]'
									)}
									aria-pressed={working[qi]?.other ?? false}
									onClick={() => pickOther(qi, multi)}
								>
									<Indicator chosen={working[qi]?.other ?? false} round={!multi} />
									<span className="flex min-w-0 flex-col gap-[0.05rem]">
										<span className="font-[450]">Other…</span>
									</span>
								</button>
								{working[qi]?.other && (
									<input
										className={TEXT_INPUT}
										value={working[qi]?.custom ?? ''}
										onChange={(event) => patch(qi, { custom: event.target.value })}
										placeholder="Type your answer"
									/>
								)}
							</>
						)}
					</div>
				) : (
					<div className="flex flex-col gap-2">
						{asRecords(q.inputs).map((input, ii) => {
							const type = inputType(input);
							return (
								<label className="flex flex-col gap-1" key={ii}>
									<span className="font-medium">
										{asString(input.label)}
										{asString(input.formPathLabel) && (
											<em className={DESC}> → {asString(input.formPathLabel)}</em>
										)}
									</span>
									{type === 'multiline' ? (
										<textarea
											className={TEXT_INPUT}
											rows={3}
											value={working[qi]?.inputs[ii] ?? ''}
											onChange={(event) => setInput(qi, ii, event.target.value)}
										/>
									) : (
										<input
											className={TEXT_INPUT}
											type={type === 'password' ? 'password' : 'text'}
											value={working[qi]?.inputs[ii] ?? ''}
											onChange={(event) => setInput(qi, ii, event.target.value)}
										/>
									)}
								</label>
							);
						})}
					</div>
				)}
			</div>
		);
	}

	return (
		<section className="my-1 flex flex-col gap-[0.7rem] rounded-sm border border-line bg-ink/3.5 px-[0.85rem] py-3 text-[12.5px] text-ink">
			{pending && !done ? (
				<>
					<header className={HEAD}>
						<span>Please answer to continue</span>
						{questions.length > 1 && (
							<span className="flex-none font-semibold tabular-nums text-muted">
								{step + 1}/{questions.length}
							</span>
						)}
					</header>

					{questions[step] && renderQuestionCard(questions[step]!, step)}

					<div className="mt-[0.15rem] flex items-center gap-[0.6rem]">
						{step > 0 && (
							<button
								type="button"
								className={BTN_SKIP}
								disabled={submitting}
								onClick={() => setStep((s) => Math.max(0, s - 1))}
							>
								Back
							</button>
						)}
						{isLast ? (
							<button
								type="button"
								className={BTN_SUBMIT}
								disabled={submitting}
								onClick={() => send('submit')}
							>
								Submit
							</button>
						) : (
							<button
								type="button"
								className={BTN_SUBMIT}
								disabled={submitting}
								onClick={() => setStep((s) => Math.min(questions.length - 1, s + 1))}
							>
								Next
							</button>
						)}
						<button
							type="button"
							className={BTN_SKIP}
							disabled={submitting}
							onClick={() => send('dismiss')}
						>
							Skip
						</button>
					</div>
				</>
			) : (
				<>
					<header className={HEAD}>{dismissed ? 'Questions skipped' : 'Answers submitted'}</header>
					{questions.map((q, qi) => (
						<div className="flex flex-col" key={qi}>
							<span className="font-medium">{asString(q.question)}</span>
							<span className="text-muted">{answerText(qi) || '—'}</span>
						</div>
					))}
				</>
			)}
		</section>
	);
}

// examples/chat-demo/src/lib/components/QuestionsCell.svelte
<script lang="ts">
	import Check from "@lucide/svelte/icons/check";
	import {
		asRecords,
		asString,
		asStrings,
		getCellPayload,
		type CellLike,
	} from "$lib/cells";
	import { toast } from "svelte-sonner";

	// onAnswered lets the page re-attach its watch stream so the resumed run's
	// cells show up (submitting halts → resumes the run on the backend).
	let { cell, onAnswered }: { cell: CellLike; onAnswered?: () => void } =
		$props();

	// Cell payloads arrive as untyped proto JSON; read them with the same
	// coercion helpers the rest of the demo uses (enums are string names).
	const payload = $derived(getCellPayload(cell));
	const status = $derived(asString(payload.status));
	const questions = $derived(asRecords(payload.questions));
	const summary = $derived(asRecords(payload.answers));
	const pending = $derived(status === "" || status.endsWith("PENDING"));
	const dismissed = $derived(status.endsWith("DISMISSED"));

	type Working = {
		selected: string[];
		custom: string;
		other: boolean;
		inputs: string[];
	};
	let working = $state<Working[]>([]);
	let submitting = $state(false);
	let done = $state(false); // optimistic: hide the form as soon as we submit
	let step = $state(0); // one-question-at-a-time cursor into `questions`

	const blank = (q: Record<string, unknown>): Working => ({
		selected: [],
		custom: "",
		other: false,
		inputs: asRecords(q.inputs).map(() => ""),
	});

	let initId = "";
	$effect(() => {
		const id = asString(cell.id);
		const reset = id !== initId;
		if (reset) {
			initId = id;
			step = 0;
		}
		if (reset || working.length !== questions.length) {
			working = questions.map((q, i) =>
				reset ? blank(q) : (working[i] ?? blank(q)),
			);
		}
		// keep the cursor in range if the question set shrinks
		if (step > questions.length - 1) step = Math.max(0, questions.length - 1);
	});

	const isLast = $derived(step >= questions.length - 1);
	function next() {
		if (step < questions.length - 1) step += 1;
	}
	function back() {
		if (step > 0) step -= 1;
	}

	function kindOf(
		q: Record<string, unknown>,
	): "choice" | "multichoice" | "inputs" {
		const k = asString(q.kind);
		if (k.endsWith("MULTICHOICE")) return "multichoice";
		if (k.endsWith("INPUTS")) return "inputs";
		return "choice";
	}
	function inputType(
		input: Record<string, unknown>,
	): "text" | "multiline" | "password" {
		if (input.sensitive === true) return "password";
		return asString(input.kind).endsWith("MULTILINE")
			? "multiline"
			: "text";
	}

	function pickChoice(qi: number, name: string) {
		working[qi].selected = [name];
		working[qi].other = false;
	}
	function pickOther(qi: number, multi: boolean) {
		if (multi) {
			working[qi].other = !working[qi].other;
		} else {
			working[qi].selected = [];
			working[qi].other = true;
		}
	}
	function toggleMulti(qi: number, name: string) {
		const set = new Set(working[qi].selected);
		if (set.has(name)) set.delete(name);
		else set.add(name);
		working[qi].selected = [...set];
	}

	function answerText(qi: number): string {
		const ans = summary[qi];
		const server = ans
			? [
					...asStrings(ans.selected),
					asString(ans.custom),
					...asStrings(ans.inputs),
				].filter(Boolean)
			: [];
		if (server.length) return server.join(", ");
		const w = working[qi];
		if (!w) return "";
		const local = [
			...w.selected,
			w.other ? w.custom : "",
			...w.inputs,
		].filter(Boolean);
		return local.join(", ");
	}

	async function send(action: "submit" | "dismiss") {
		submitting = true;
		try {
			const answers = working.map((w, i) => {
				const inputs = asRecords(questions[i].inputs);
				return {
					selected: w.selected,
					custom: w.other && w.custom ? w.custom : undefined,
					inputs: w.inputs,
					provided: inputs.map(
						(_, j) => (w.inputs[j] ?? "").length > 0,
					),
				};
			});
			const res = await fetch("/api/questions", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({
					action,
					cellId: asString(cell.id),
					answers,
				}),
			});
			if (!res.ok) {
				const body = (await res.json().catch(() => ({}))) as {
					error?: string;
				};
				throw new Error(body.error ?? `Request failed (${res.status})`);
			}
			done = true;
			onAnswered?.();
			toast.success(
				action === "submit" ? "Answers submitted" : "Questions skipped",
			);
		} catch (err) {
			toast.error(
				err instanceof Error ? err.message : "Failed to send answers.",
			);
		} finally {
			submitting = false;
		}
	}
</script>

{#snippet indicator(chosen: boolean, round: boolean)}
	<span class="indicator" class:round class:on={chosen}>
		{#if chosen}
			{#if round}<span class="dot"></span>{:else}<Check
					size={11}
					strokeWidth={3}
				/>{/if}
		{/if}
	</span>
{/snippet}

{#snippet questionCard(q: Record<string, unknown>, qi: number)}
	{@const kind = kindOf(q)}
	<div class="question">
		<p class="question-title">{asString(q.question)}</p>
		{#if asString(q.explanation)}
			<p class="question-explain">{asString(q.explanation)}</p>
		{/if}

		{#if kind === "choice" || kind === "multichoice"}
			{@const multi = kind === "multichoice"}
			<div class="options">
				{#each asRecords(q.options) as opt (asString(opt.name))}
					{@const name = asString(opt.name)}
					{@const chosen =
						working[qi]?.selected.includes(name) ?? false}
					<button
						type="button"
						class="option"
						class:selected={chosen}
						aria-pressed={chosen}
						onclick={() =>
							multi
								? toggleMulti(qi, name)
								: pickChoice(qi, name)}
					>
						{@render indicator(chosen, !multi)}
						<span class="option-body">
							<span class="option-name">{name}</span>
							{#if asString(opt.description)}
								<span class="option-desc"
									>{asString(opt.description)}</span
								>
							{/if}
						</span>
					</button>
				{/each}
				{#if q.allowCustom === true}
					{@const chosen = working[qi]?.other ?? false}
					<button
						type="button"
						class="option"
						class:selected={chosen}
						aria-pressed={chosen}
						onclick={() => pickOther(qi, multi)}
					>
						{@render indicator(chosen, !multi)}
						<span class="option-body"
							><span class="option-name">Other…</span
							></span
						>
					</button>
					{#if chosen}
						<input
							class="text-input"
							bind:value={working[qi].custom}
							placeholder="Type your answer"
						/>
					{/if}
				{/if}
			</div>
		{:else}
			<div class="inputs">
				{#each asRecords(q.inputs) as input, ii (ii)}
					{@const type = inputType(input)}
					<label class="field">
						<span class="field-label">
							{asString(input.label)}
							{#if asString(input.formPathLabel)}
								<em class="option-desc"
									>→ {asString(input.formPathLabel)}</em
								>
							{/if}
						</span>
						{#if type === "multiline"}
							<textarea
								class="text-input"
								rows="3"
								bind:value={working[qi].inputs[ii]}
							></textarea>
						{:else}
							<input
								class="text-input"
								type={type === "password" ? "password" : "text"}
								bind:value={working[qi].inputs[ii]}
							/>
						{/if}
					</label>
				{/each}
			</div>
		{/if}
	</div>
{/snippet}

<section class="questions" class:resolved={!pending || done}>
	{#if pending && !done}
		<header class="questions-head">
			<span>Please answer to continue</span>
			{#if questions.length > 1}
				<span class="progress">{step + 1}/{questions.length}</span>
			{/if}
		</header>

		{#if questions[step]}
			{@render questionCard(questions[step], step)}
		{/if}

		<div class="actions">
			{#if step > 0}
				<button
					type="button"
					class="btn-skip"
					disabled={submitting}
					onclick={back}
				>
					Back
				</button>
			{/if}
			{#if isLast}
				<button
					type="button"
					class="btn-submit"
					disabled={submitting}
					onclick={() => send("submit")}
				>
					Submit
				</button>
			{:else}
				<button
					type="button"
					class="btn-submit"
					disabled={submitting}
					onclick={next}
				>
					Next
				</button>
			{/if}
			<button
				type="button"
				class="btn-skip"
				disabled={submitting}
				onclick={() => send("dismiss")}
			>
				Skip
			</button>
		</div>
	{:else}
		<header class="questions-head">
			{dismissed ? "Questions skipped" : "Answers submitted"}
		</header>
		{#each questions as q, qi (qi)}
			<div class="answered">
				<span class="answered-q">{asString(q.question)}</span>
				<span class="answered-a">{answerText(qi) || "—"}</span>
			</div>
		{/each}
	{/if}
</section>

<style>
	.questions {
		border: 1px solid var(--color-line);
		border-radius: var(--radius-sm, 10px);
		padding: 0.75rem 0.85rem;
		margin: 0.25rem 0;
		background: color-mix(in srgb, var(--color-ink) 3.5%, transparent);
		display: flex;
		flex-direction: column;
		gap: 0.7rem;
		font-size: 12.5px;
		color: var(--color-ink);
	}
	.questions-head {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 0.5rem;
		font-weight: 600;
		font-size: 12px;
		letter-spacing: 0.01em;
		color: var(--color-muted);
	}
	.progress {
		flex: 0 0 auto;
		font-variant-numeric: tabular-nums;
		font-weight: 600;
		color: var(--color-muted);
	}
	.question {
		display: flex;
		flex-direction: column;
		gap: 0.35rem;
	}
	.question-title {
		font-weight: 500;
		font-size: 13px;
		margin: 0;
	}
	.question-explain,
	.option-desc {
		font-size: 11.5px;
		color: var(--color-muted);
		font-style: normal;
		margin: 0;
	}
	.options {
		display: flex;
		flex-direction: column;
		gap: 0.3rem;
	}
	/* Selectable card: neutral by default, accent border + tint when picked. */
	.option {
		display: flex;
		align-items: flex-start;
		gap: 0.5rem;
		width: 100%;
		text-align: left;
		font: inherit;
		font-size: 12.5px;
		color: var(--color-ink);
		padding: 0.4rem 0.55rem;
		border: 1px solid var(--color-line);
		border-radius: var(--radius-xs, 6px);
		background: color-mix(in srgb, var(--color-paper) 60%, var(--color-elevate));
		cursor: pointer;
		transition:
			border-color 0.12s ease,
			background 0.12s ease;
	}
	.option:hover {
		border-color: color-mix(
			in srgb,
			var(--color-accent) 45%,
			var(--color-line)
		);
	}
	.option.selected {
		border-color: var(--color-accent);
		background: color-mix(in srgb, var(--color-accent) 8%, var(--color-elevate));
	}
	.option:focus-visible {
		outline: 2px solid var(--color-accent);
		outline-offset: 1px;
	}
	/* Custom radio/checkbox indicator so the picked state reads clearly. */
	.indicator {
		flex: 0 0 auto;
		width: 15px;
		height: 15px;
		margin-top: 1px;
		border: 1.5px solid
			color-mix(in srgb, var(--color-ink) 25%, transparent);
		border-radius: 4px;
		display: flex;
		align-items: center;
		justify-content: center;
		color: #fff;
		transition:
			border-color 0.12s ease,
			background 0.12s ease;
	}
	.indicator.round {
		border-radius: 50%;
	}
	.option.selected .indicator {
		border-color: var(--color-accent);
		background: var(--color-accent);
	}
	.option.selected .indicator.round {
		background: #fff;
	}
	.dot {
		width: 7px;
		height: 7px;
		border-radius: 50%;
		background: var(--color-accent);
	}
	.option-body {
		display: flex;
		flex-direction: column;
		gap: 0.05rem;
		min-width: 0;
	}
	.option-name {
		font-weight: 450;
	}
	.inputs {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}
	.field {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}
	.field-label {
		font-weight: 500;
	}
	.text-input {
		font: inherit;
		font-size: 12.5px;
		padding: 0.35rem 0.55rem;
		border: 1px solid var(--color-line);
		border-radius: var(--radius-xs, 6px);
		background: var(--color-elevate);
		width: 100%;
		color: var(--color-ink);
	}
	.text-input:focus-visible {
		outline: 2px solid var(--color-accent);
		outline-offset: -1px;
		border-color: transparent;
	}
	.actions {
		display: flex;
		align-items: center;
		gap: 0.6rem;
		margin-top: 0.15rem;
	}
	.btn-submit {
		font: inherit;
		font-size: 12px;
		font-weight: 500;
		padding: 0.32rem 0.85rem;
		border: 0;
		border-radius: var(--radius-xs, 6px);
		background: var(--color-accent);
		color: #fff;
		cursor: pointer;
		transition: background 0.12s ease;
	}
	.btn-submit:hover {
		background: color-mix(in srgb, var(--color-accent) 88%, #000);
	}
	.btn-skip {
		font: inherit;
		font-size: 12px;
		padding: 0.32rem 0.3rem;
		border: 0;
		background: transparent;
		color: var(--color-muted);
		cursor: pointer;
	}
	.btn-skip:hover {
		color: var(--color-ink);
	}
	.btn-submit:disabled,
	.btn-skip:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}
	.answered {
		display: flex;
		flex-direction: column;
	}
	.answered-q {
		font-weight: 500;
	}
	.answered-a {
		color: var(--color-muted);
	}
</style>
